### ISSUE TITLE
Warning: preg_replace(): Compilation failed: unmatched parentheses

### ISSUE THREAD

**Issue by mudrd8mz** [michael-milette/moodle-filter_filtercodes#1]
After enabling the filter, I see a lot of PHP warnings
```
Warning: preg_replace(): Compilation failed: unmatched parentheses at offset 12 in
/filter/filtercodes/filter.php on line 391
```

**Comment by mudrd8mz** [comment]
It looks like a typo - simply removing the `)` seems to fix the issue.

**Comment by mudrd8mz** [comment]
Thanks. Please make sure to have developer debugging enabled while working on plugins. This is what I always put to config.php on my dev installations:
```
@error_reporting(E_ALL | E_STRICT);
@ini_set('display_errors', '1');
$CFG->debug = (E_ALL | E_STRICT);
$CFG->debugdisplay = 1;
```
It helps to catch these kind of issues early.

**Comment by michael-milette** [comment]
Thanks - Appreciate the suggestion. Do you find adding these to Moodle's config.php improves Moodle's error reporting on top of having Moodle's Debugging > Debugging Messages setting set to "DEVELOPER: extra Moodle debug messages for developers"?

**Comment by michael-milette** [comment]
This issue has been resolved. The fix will be included in the upcoming release of FilterCodes for Moodle.

**Comment by mudrd8mz** [comment]
> Do you find adding these to Moodle's config.php improves Moodle's error reporting ...

No, it is the same mechanism. Just hard-coded in config.php so that I do not forget to set it manually via the web UI.

**Comment by michael-milette** [comment]
That's what I thought. I actually find the error reporting in debug mode to be pretty good. I've even had others ask me to test some PHP code in Moodle because it seems to report more issues than they normally can in their non-Moodle development environment. Thanks again for the code snippet @mudrd8mz. I'll be sure to share it with other developers next time it comes up if that is ok with you.

**Comment by mudrd8mz** [comment]
Sure - this and other useful dev settings can be found in https://github.com/moodle/moodle/blob/v3.3.1/config-dist.php#L555

**Comment by michael-milette** [comment]
Thanks for sharing @mudrd8mz ! Indeed, there is some interesting and useful information in that file.
