### ISSUE TITLE
Feature Request: Fullname of the profile owner

### ISSUE THREAD

**Issue by kineoalexc** [michael-milette/moodle-filter_filtercodes#103]
Working to get this installed in my environment - wanted to ask a question to see if this functionality is possible/been done. Use Case:

As a user, there's a filtercode in an html block on my profile page that shows my full name. This works great. 
As an admin when I go to that user's page, the filtercode will show MY full name, not the user's whose profile I'm on.

Is there a way via scrape/language string/other to show the User's info in this situation?

**Comment by michael-milette** [comment]
Hi @kineoalexc ,

It is certainly doable. I could create a {profilefullname} tag. On the profile page, it would display the name of the owner of that profile instead of the logged-in user's name.
Is that what you had in mind?
Best regards,
Michael

**Comment by michael-milette** [comment]
There is now a new tag called {profilefullname} included in the next release of FilterTags, currently only available here on GitHub. This tag will be included in Moodle.org/plugins upon the next public release which should be coming out a few days before the launch of Moodle 3.9 in June 2020.

Please feel free to try it out beforehand and let me know if it works for you.
