### ISSUE TITLE
filter to track unread forum {forumunread XX}

### ISSUE THREAD

**Issue by xjunin** [michael-milette/moodle-filter_filtercodes#107]
Hello, first, I would like to praise the excellent work.

I would like to know if there is a possibility to recover a counter from unread forums "eg: 1 unread message"

![Anotação 2020-05-28 163825](https://user-images.githubusercontent.com/6360970/83185650-ae53fb00-a101-11ea-84fa-4157aa06dd3f.png)

Thank you!

**Comment by michael-milette** [comment]
Hi @xjunin ,

Not yet, but if you think it would be useful, I might consider it for the future.

Can you describe to me how you might use this?

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @xjunin ,

I have been giving this issue some thought. One of the problems that I could see is that, what appears in your screenshot becomes the name of your forum. While I like the idea, I can't see people wanting their forum to be titled "XX unread messages."

As you have not responded to my previous message in almost a month, I will be closing this ticket. Please feel free to re-open if you would like to resume the discussion.
