### ISSUE TITLE
Feature request:  new tags for {profileuserid}, {profileidnumber}

### ISSUE THREAD

**Issue by golam-m-hossain** [michael-milette/moodle-filter_filtercodes#112]
Firstly, let me thank you for making this extremely useful plugin. We have recently upgraded to Moodle 3.9 and we would like to add few "Other fields" in "User profile fields" to display user specific link to another system outside Moodle.

For example, our teachers sometime would like to see the past records of a student who is enrolled in a course. We could add a link in user profile field as  `<a href="/showgradecards/{profileidnumber}/">Show Grade Cards</a>`.

If I extend the codes in "filter.php" to include {profileidnumber}, similar to what is done for {profilefullname}, then the substitution works as expected, together with relaxing the condition as  `if (($PAGE->pagelayout == 'mypublic' || $PAGE->pagelayout == 'standard') && ($PAGE->pagetype == 'user-profile' || $PAGE->pagetype == 'course-view-weeks'))`

So I would like to request you to include these two new tags {profileuserid} and {profileidnumber} in future versions.

Thanks,
Golam

**Comment by michael-milette** [comment]
Hi @golam-m-hossain ,

- For custom profile fields, look for the {profile_field_shortname} tag. 
- For the standard user ID, the tag you need is {userid}.
- For the idnumber profile field, take a look at {idnumber}.

Best regards,

Michael

**Comment by golam-m-hossain** [comment]
Hello Michael,

For the usage that I am referring to, we need both `{userid}` as well as `{profileuserid}` simultaneously. The first one belongs to the teacher whereas the second one belongs to the student.

Thanks,
Golam
