### ISSUE TITLE
Remove completed courses in {mycoursesmenu}

### ISSUE THREAD

**Issue by argwallace** [michael-milette/moodle-filter_filtercodes#114]
Hello!

I am using the most current version (2.0.0) of FilterCodes on Moodle 3.8.4. I have a custom navigation menu that is working just fine in my theme with the {mycoursemenu} tag. However, I have noticed that when a course is completed, it will be removed from the side navigation area under My Courses but it still remains in the filtercodes {mycoursesmenu}. Any way to resolve this as it gives conflicting results. Thanks!
Stephen

**Comment by michael-milette** [comment]
Hi Stephen,

That is a good point and a great idea. Probably makes a lot of sense to remove the completed courses, especially if your students tend to take a lot of courses like in a school (I work mostly with businesses, non-profits and go government). Definitely going to look into this for a future release.

Best regards,

Michael

**Comment by argwallace** [comment]
Michael,

Thanks for looking into this! Actually, I can see having an option for both could be valuable. Being able to create a menu for all enrolled courses (whether completed or not) and a current courses which showed enrolled but not completed. Any updates would be most welcome but I do understand you have many projects.

Thanks and best regards!

Stephen

**Comment by argwallace** [comment]
Hi Michael,

Just curious if there was any further development of this topic. Thanks and I appreciate the work you do.

Best regards,
Stephen

**Comment by michael-milette** [comment]
Hi Stephen,

There has not been any further development, however, I really appreciate the reminder as I was looking through the tickers just a few days ago deciding on what to work on next so this is good timing. I will not be able to work on this for a few weeks now but if you want to contribute, even if it is to point me to some other code that does something similar elsewhere, I would be happy to work on this with you.

Best regards,

Michael

**Comment by argwallace** [comment]
Hi Michael,

I have tried to look into the code on both Moodle and FilterCodes to see if I find how the enrolled courses get created. They both use the same function of “enrol_get_my_courses()” but I am not sure why in the navigation bar side of things it doesn’t show my completed courses but in the FilterCodes mycoursesmenu, it does. I wish I knew more of the code an dhow this worked because at first glance I couldn’t see any stark differences that would return different results.

I wish I could have been more helpful.

Thanks,

Stephen

**Comment by michael-milette** [comment]
Hi @argwallace 

I am starting to work on this.

In the process, please note that I removed the Request a Course link from the from the course list. The functionality is still there but you will need to add a {courserequestmenu} tag. I know it has nothing to do with your request but I thought I would mention it in case you do use it. There is also a new {courserequestmenu0} tag in case you need a top level custom menu link.

I will give you more news when I have some for you.

Best regards,

Michael

**Comment by argwallace** [comment]
Michael,

That’s great! Let me know if you want to me test anything. I’d be happy to do that.

Bets regards,

Stephen

**Comment by michael-milette** [comment]
Hi @argwallace ,

I just added a new FilterCodes setting to allow you to hide completed courses in the {mycoursesmenu} tag.

![image](https://user-images.githubusercontent.com/3808579/116655019-539dd180-a958-11eb-89ac-0f0b236ad37d.png)

This feature is currently only available in the version here on GitHub. If you would be so kind as to give it a try and let me know if this works for you, I would really appreciate it. If this meets your requirements, I will then include it in the upcoming release of FilterCodes on Moodle.org. It should be coming out in the next few weeks, around the same time as Moodle 3.11.

Best regards,

Michael Milette

**Comment by argwallace** [comment]
Michael,

Thank you!! I will test this and get back to you!

Best regards,

Stephen

**Comment by argwallace** [comment]
Michael,

I have installed this update and it is working as intended. I turn it on and the completed courses are not shown. I re-enable the option and the courses re-appear.

THANK YOU!

Let me know if you would like me to test anything else…

Stephen

**Comment by Richardvi** [comment]
I just found this threat, but is there a delay on this? I have some courses with an end-date of 2019, yet they still show up in the 'mycoursesmenu'. I have checked the option to hide completed courses.

**Comment by michael-milette** [comment]
Hi @Richardvi ,

What version of FilterCodes are you using? Also, did you check the box in the FilterCodes settings?

![image](https://github.com/michael-milette/moodle-filter_filtercodes/assets/3808579/f29050eb-f878-494f-aa18-7858b910c770)

**Comment by michael-milette** [comment]
Hi @Richardvi - Looks like the code to address went missing in recent versions. Let me get back to you on that.

**Comment by michael-milette** [comment]
Hi @Richardvi 

After reviewing this ticket and the code, this ticket relates to the removal of completed courses, not expired courses from the list. 

So, if you are enrolled in a course that you did not complete before the end date of the course, the course will still show up in the menu.

Best regards,

Michael

**Comment by Richardvi** [comment]
Ah yes thanks! That makes sense. Sorry for misunderstanding this option :)
