### ISSUE TITLE
Implement a {mygroups} filter

### ISSUE THREAD

**Issue by jprovasnik** [michael-milette/moodle-filter_filtercodes#116]
Currently, to have three sets of assignment instructions for students (in three different groups), the core method would be to create 4 different assignments. The issue with this method is how the gradebook works -- teachers would have to be knowledgable of how to aggregate the gradebook (or build sub-categories with varying aggregations) to ensure each child is being evaluated out of the same amount of points. 

Another core method is to create 4 page modules where the group-specific Instructions can go (and a separate assignment submission box). Then the teacher just needs to group each page module to a specific group. But, for teachers who want to restrict the student from accessing the submission box prior to reading the separated instructions, the teacher then has to create a restriction set and set up so the student must have viewed any one of the four instruction pages. This requires the teacher to have to make lots of fine-tuned settings and can get extremely tedious when wanting to quickly add a new assignment. 

This feature request is to help alleviate all of the above for teachers who are not so familiar with LMSs and just want to "teach" (and not be instructional system designers!). A {my groups} filter will allow teachers to go back to just using one assignment and they can list all sets of directions in one place, but students would only see the directions that pertain to them or have access to links that pertain to them. 

(Stems off of [53](https://github.com/michael-milette/moodle-filter_filtercodes/issues/53))

Visual Example: 

![Proposal](https://user-images.githubusercontent.com/44345287/91111856-91bb5680-e64f-11ea-8db7-59fdb9500f36.png)
![Core Method 2](https://user-images.githubusercontent.com/44345287/91111864-941db080-e64f-11ea-82b6-ef7ff0c710bc.png)
![Core Method 1](https://user-images.githubusercontent.com/44345287/91111865-94b64700-e64f-11ea-8bff-797390f1b67b.png)

**Comment by michael-milette** [comment]
Hi @jprovasnik 

How is would this feature be different than the request for #53 - other than the syntax? It seems to me that your suggestion would result in the exact same functionality.

Michael

**Comment by jprovasnik** [comment]
I think we can close this since it's the same as #53.
