### ISSUE TITLE
{coursecards} for specific category ids

### ISSUE THREAD

**Issue by jb-fol** [michael-milette/moodle-filter_filtercodes#118]
Love the coursecards feature - is it possible to specify that courses come from one specific category id (or even an array of category ids)? Eg. {coursecards id=2} or {coursecards id=2,5,7}

**Comment by michael-milette** [comment]
Great idea! Thanks for the suggestion.

**Comment by michael-milette** [comment]
Hi @jb-fol 

I am please to let you know that the {coursecards} tag can now take one optional parameter, the ID of a category. Example {coursecards 2}.

The tag's new feature is currently only available on GitHub and but is ready for testing. If you have a few minutes, please give it a try and let me know if it works for you.

If it all works out, this new feature will be included in the next release of FilterCodes on Moodle.org in May 2021, around the same time as the release of Moodle 3.11.

Best regards,

Michael Milette

**Comment by mattgig** [comment]
When you use a category number which doesn't exist in a label, you will get an "unknown category" error and you won't be able to correct your mistake through the user interface unless you disable the filter or you use some other tricks to edit the label . (Tested with Moodle 3.10.1, Build: 20210118)

**Comment by michael-milette** [comment]
Thank you @mattgig - I really appreciate that feedback and will fix the problem.

**Comment by michael-milette** [comment]
Hi @mattgig ,

Thanks again for the feedback. The problem with invalid and inaccessible course categories has been fixed. In both cases, the tag will act as if there are no courses in that category.

If you can try it out again, I would really appreciate it.

Best regards,

Michael

**Comment by mattgig** [comment]
Hi Michael

I have just done some testing. Your code now works even if a user does something silly.
I have tested:

- numbers which don't exist, including negative ones.
- Letters such as A and ä.
- very long strings.

Thanks for your ongoing engagement.

Best regards
Matthias

**Comment by michael-milette** [comment]
You are welcome. I really appreciate to hear that you findnit useful. Thank you for testing it out Matthias. I really appreciate your efforts and helpful feedback too.

Best regards,

Michael
