### ISSUE TITLE
Custom menu patch does not work in Moodle 3.9

### ISSUE THREAD

**Issue by patgaytx** [michael-milette/moodle-filter_filtercodes#120]
i'm using moodle 3.9 and the boost theme and FilterCodes [2.0.0] 2020-07-01. I found /moodle/theme/boost/classes/output/core_renderer.php and I've tried to add the code from https://github.com/michael-milette/moodle-filter_filtercodes/blob/master/README.md#user-content-for-themes-based-on-boost to the end of that file, but it blows up with an error about the theme_boost already being declared on line 0.

From Michael:
Hi Patrick,
I am not sure that it is you. I did not realize it but suspect the compatibility of that code snippets to support FilterCodes in the custom menu may have ended with Moodle 3.8. I will need to take a look at it and see what is going on as I will be needing that functionality myself for a project  upgrade within about a month or so.
If you want to be kept up to date regarding this issue, please open an issue ticket at https://github.com/michael-milette/moodle-filter_filtercodes/issues

**Comment by michael-milette** [comment]
Just to be clear, FilterCodes does work in Moodle 3.9. It is the patch in the documentation which does not.

Just out of curiosity, what is Moodle's default language? I ask because I have noticed some issues when using English Workplace language pack with the regular Moodle.

**Comment by michael-milette** [comment]
Hi @patgaytx 

Just to help you move forward, I wanted to let you know that I am in the process of updating related parts of the README.md file. The links and related code were outdated. Please take a look at #133 a the solution on how to patch Moodle to get it working in Moodle 3.7, 3.8 and 3.9.

As for the snippet in the documentation, I have not yet had time to review and update it.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @patgaytx see #148 in case this affects you.

**Comment by michael-milette** [comment]
Hi @patgaytx , I recently updated the source code in the README.md file. It will be published here on GitHub soon and on Moodle.org with the next release of FilterCodes later this month.

You never did really define what "blows up" means. However, new in Moodle 3.9 is the **Convert URLs into links and images** filter (a.k.a. urltolink) which is enabled by default. This can be the cause of your issue. I added it to the list of filters to be skipped in the core_renderer code and that seems to have done the trick. No more "blow-ups" :-)

Between this and the rest of the recommendations previously listed in this ticket, if you find that this does not resolve your issue, please feel free to re-open this issue or create a new ticket.

Best regards,

Michael
