### ISSUE TITLE
Bug: Tag for alert boxes is missing

### ISSUE THREAD

**Issue by michael-milette** [michael-milette/moodle-filter_filtercodes#123]
On the FilterCodes plugin page on Moodle.org, it says that you can create alert type boxes however none of the tags seem to do this.

**Comment by paresh27** [comment]
Can you assign it to me? Also it would be better if you share a screen shot of where is this issue coming from?

**Comment by michael-milette** [comment]
Hi @paresh27 ,

Thank you for your offer. I would welcome your contribution.

The basic code for the {alert} tag is already there (I forgot to include it in the last release). However, I my intention is to add support for different types of Bootstrap alerts boxes including:

{alert primary}Primary content{/alert}
{alert secondary}Secondary content{/alert}
{alert success}Success content{/alert}
{alert danger}Danger content{/alert}
{alert warning}Warning content{/alert}
{alert info}Info content{/alert}
{alert light}Light content{/alert}
{alert dark}Dark content{/alert}

If no type is specified, the default {alert}Warning content{/alert} should result in the same as {alert warning}.

Using the Boost theme for Moodle 3.9, the above examples should end up looking like:
![image](https://user-images.githubusercontent.com/3808579/95001498-85081780-0598-11eb-908f-abfceb383012.png)

More information on Bootstrap 4 **Alert** component:
https://getbootstrap.com/docs/4.0/components/alerts/

If you are still interested, please confirm and I will assign it to you. Please be sure to review the file called CONTRIBUTING.md included in this repository.

Best regards,

Michael

**Comment by paresh27** [comment]
I guess it is done, isn't it?

**Comment by vpn** [comment]
> I guess it is done, isn't it?

It's in progress over at this pull request #125

**Comment by vpn** [comment]
@michael-milette 
Could you add `hacktoberfest` to your repository topic? 
![fork screenshot](https://i.imgur.com/df53kP3.png)
![Ineligible Repository](https://i.imgur.com/dQ6wP2p.png)

**Comment by michael-milette** [comment]
> I guess it is done, isn't it?

Hi @paresh27 , it is indeed done. However, if you would like to do another enhancement, take a look at the list of issues. There are several that are tagged hacktoberfest which might be of interest to you. I am also open to new feature ideas if you have a need for enhancements in your Moodle installation.

Best regards,

Michael
