### ISSUE TITLE
Broken github links in README.md

### ISSUE THREAD

**Issue by luisdev** [michael-milette/moodle-filter_filtercodes#133]
The "My theme does not support filters in the menu and the developer does not want to fix the theme" section of the README.md file ( https://github.com/michael-milette/moodle-filter_filtercodes#my-theme-does-not-support-filters-in-the-menu-and-the-developer-does-not-want-to-fix-the-theme-what-can-i-do ) links to three github.com links:

- Moodle 3.7: https://github.com/michael-milette/moodle/tree/MDL-61750-M37
- Moodle 3.8: https://github.com/michael-milette/moodle/tree/MDL-61750-M38
- Moodle master (3.9 and beyond): https://github.com/michael-milette/moodle/tree/MDL-61750-master

Those github.com links are broken (404).

**Comment by michael-milette** [comment]
Thanks for letting me know @luisdev . I will be rebasing and reposting these soon.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @luisdev ,

Here are the updated links:

* Moodle 3.7: https://github.com/michael-milette/moodle/tree/MDL-63219-M37
* Moodle 3.8: https://github.com/michael-milette/moodle/tree/MDL-63219-M38
* Moodle 3.9: https://github.com/michael-milette/moodle/tree/MDL-63219-M39

I will update them in the [README.md](https://github.com/michael-milette/moodle-filter_filtercodes#my-theme-does-not-support-filters-in-the-menu-and-the-developer-does-not-want-to-fix-the-theme-what-can-i-do)  file shortly.

TIP: You can easily apply a patch to any instance of Moodle that was installed using git by applying the following command (change the **M39** to the version of your Moodle as seen in the links above):

    git remote add michaelmilette https://github.com/michael-milette/moodle.git
    git cherry-pick michaelmilette/MDL-63219-**M39**

Thanks again for taking the time to bringing this issue to my attention. I really appreciate your support.

Best regards,

Michael
