### ISSUE TITLE
Custom profile field does not work when the type is textarea.

### ISSUE THREAD

**Issue by FurloSK** [michael-milette/moodle-filter_filtercodes#134]
Hi,

I just noticed that {profile_field_shortname} filter code does not expand when the type of custom profile field is multiline text area.

I tested it by using the text area profile field (named multiline → {profile_field_multiline}) just next to our other custom profile fields of all other types. All of them expanded, except the multiline field.

**Comment by michael-milette** [comment]
Hi @FurloSK ,

Thank you for brining this to my attention. I will take a look at this as soon as I have a chance and will let you know if I have any questions.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @FurloSK ,

Thank you again for bringing this to my attention. The {profile_field_shortname} tag now supports textarea multi-line custom fields. This fix is now available on GitHub and will be included in the next release of FilterCodes on Moodle.org within a couple of days.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
The latest version, including the fix, has been released on Moodle.org.
