### ISSUE TITLE
Add extra fields for preferred language and timezone

### ISSUE THREAD

**Issue by davefoord** [michael-milette/moodle-filter_filtercodes#135]
I work on a multi-language global Moodle, where people see different content based on their preferred language, and also we use tools like the scheduler activity a lot, which converts times into people's timezones - but both these only work, if the person's language and timezone is set correctly. I would love to use the filtercodes plugin to highlight to them what their timezone is currently set to (e.g. within each scheduler activity), and highlight what language they are set to e.g. at the top of each course - so they can change these easily if necessary.

Thanks in advance,

**Comment by michael-milette** [comment]
That is an excellent use case. I will definitely look this. Thank you @davefoord !

**Comment by michael-milette** [comment]
Would you want the ISO language code or the full name? I am assuming the full name in the current UI language.

**Comment by davefoord** [comment]
I would want the full name - as the ISO code won't mean much to the user. e.g. if someone has chosen Espanol (Colombian) I would want to see either:

Espanol - Colombia (es_co)
Espanol - Colombia

Thanks

**Comment by michael-milette** [comment]
Hi @davefoord , a new tag {timezone} has been added to FilterCodes and will be included in the next release within the next couple of days. Thank you for the suggestion!

(preferred language will be coming soon)

**Comment by michael-milette** [comment]
Hi @davefoord , a new tag {preferredlanguage} has been added to FilterCodes and will be included in the next release within the next couple of days.

Note: Because the language will be displayed in the that language and not in Moodle's current language, it will be enclosed in a span tag with an appropriate lang="..." attribute so that screen readers pronounce it correctly.

Feel free to try out the new {timezone} and {preferredlanguage} tags before that by downloading and installing FilterCodes directly from GitHub.

Thank you again for your suggestion!

Best regards,

Michael

**Comment by davefoord** [comment]
Hi Michael, thanks for adding in the filter codes for {timezone} and {preferredlanguage} I have tested these on my test moodle and they work great.

When are you going to release this update to the plugins page? My host company for my live moodle prefers to only apply plugin updates once they are published there.

**Comment by michael-milette** [comment]
Hi @davefoord ,

You are very welcome. I am just in the process of doing compatibility testing with the recently released Moodle 3.10. I hope to have the new release available on Moodle.org by sometime this coming weekend.

Best regards,

Michael

**Comment by michael-milette** [comment]
The latest version, including these new tags, has been released on Moodle.org.

**Comment by davefoord** [comment]
Yes – thanks for this, I have downloaded, installed and already using – looks great.

 

Dave Foord

A6 Training and Consultancy Ltd

Email:  <mailto:dave@a6training.co.uk> dave@a6training.co.uk

Tel: 07922115678

Web:  <http://www.a6training.co.uk/> www.a6training.co.uk

Twitter: @davefoord
