### ISSUE TITLE
Feature Request: Conditional filters based on last login into course/course progress/activity progress

### ISSUE THREAD

**Issue by benutzer-prog** [michael-milette/moodle-filter_filtercodes#139]
It would be great to show for example an bootstrap alert for the user on reopening an scorm package/quiz/book, that was updated  since the last login of the user in the course. And only, if the user completed or tried the activity the last time (because everybody who's new to the activity doesn't need to know what's new).

**Comment by michael-milette** [comment]
Would that functionality not be available through the use of the latest Announcements block?

**Comment by michael-milette** [comment]
Hi @benutzer-prog ,

As it has been 2.5 months since I last heard from you, I will assume that you found a solution and will close this ticket. If that is not the case, please feel free to re-open this ticket or create a new one.

Best regards,

Michael
