### ISSUE TITLE
Feature Request: Get current activity ID

### ISSUE THREAD

**Issue by dhackinstitute** [michael-milette/moodle-filter_filtercodes#140]
Hello Michael,

Thanks for the awesome plugin! The {sesskey} is especially useful to me.

I'm not sure if this is already supported but I was wondering: is there a way to get the ID of the current activity (page, assignment, quiz, etc.)? For example, getting the "483" in the URL https://moodle.com/mod/page/view.php?id=483.

Along with the user and course IDs, this can be useful when talking to an external system e.g. creating a unique string from these three fields.

**Comment by michael-milette** [comment]
Hi @dhackinstitute 

Within a course, there is a {courseid} (%7Bcourseid%7D) and a {sectionid} but no {activityid}. Can you give me an example of how you would use this?

Best regards,

Michael

**Comment by dhackinstitute** [comment]
Thank you for writing back Michael.

One of the things we do is pull "base projects" from a database to load on a Moodle page. Those projects are unique to each activity on Moodle so it will be useful to query the database using the activity ID and not just the user and course ID.

**Comment by michael-milette** [comment]
Hi @dhackinstitute ,

Can you give me an idea of how you do that? I just want to make sure that, if I do this, that it will work for you.

Best regards,

Michael

**Comment by dhackinstitute** [comment]
Hi @michael-milette ,

So we have iframes on pages in Moodle. The "src" will be based on userid, courseid, and activityid. Using filtercodes, I'm able to get userid and courseid. However, since activityid is not available, we use JS to get the activityid and then set the "src" using JS.

**Comment by michael-milette** [comment]
Hi @dhackinstitute , that is exactly the information I needed. Thank you!

**Comment by michael-milette** [comment]
Hi @dhackinstitute, could you tell me which activities you will be using this with? Also, is the activity id that you want always the id parameter in the URL?

**Comment by michael-milette** [comment]
Hi @dhackinstitute ,

I think I have something for you. Give this version of FilterCodes a try. In it, I've included a new tag called **%7Bcoursemoduleid%7D** which you can use in a URL to provide a course module activity ID.

Let me know if this meets your requirement. If it does, I will merge it into the main version of FilterCodes in the May 2021 release of FilterCodes on Moodle.org.

Best regards,

Michael Milette

**Comment by dhackinstitute** [comment]
It works perfectly! Thank you, Michael! I can get rid of the extra JavaScript code I was using.

**Comment by michael-milette** [comment]
Hi @dhackinstitute ,

Thank you for testing and for the positive feedback. I've integrated the new tag into the master branch here on GitHub. It be included in the May 2021 release on Moodle.org.

Thank you again for your help in making FilterCodes useful and better for everyone.

Best regards,

Michael Milette
