### ISSUE TITLE
Date type custom profile field displayed incorrectly

### ISSUE THREAD

**Issue by davefoord** [michael-milette/moodle-filter_filtercodes#143]
If a user profile field is set up as a date, when this is added to an activity/resource as a filter code, it displays this as a long number, rather than a usable date format. Would it be possible for this to be displayed as a date format?

**Comment by michael-milette** [comment]
Thank you for reporting this. When I created the Filtercodes tag for custom profile fields, I did not take into account the field type. Will definitely look into fixing this.

**Comment by michael-milette** [comment]
Hi @davefoord ,

I just came across a temporary fix that might be of interest to you. It's plugin called https://moodle.org/plugins/filter_formattimestamp 

 I am still hoping to include a fix this issue the next release FilterCodes in May 2021. However, if you need a solution today, the Format Timestamp filter might be a workaround. That said, keep in mind that I am not sure what will happen after I fix this issue if your date is wrapped in a set of Format Timestamp tags. You can try this for yourself by wrapping it around an actual date as text.

**Comment by davefoord** [comment]
Thanks for getting back to me. I will wait until your update in May. I don't want to introduce more complications to the mix.

Thanks for all your work on this plugin - I have very quickly found lots of really good uses for it.

**Comment by michael-milette** [comment]
Hi @davefoord ,

The Data/Time field will now display a date and optionally a time if enabled instead of a number.

The Checkbox type field will now display "Yes" if checked or "No" if not checked instead of 1 and 0.

These fixes are currently only available in the version available from GitHub. If you have time, please give it a try and let me know if it works for you.

If everything works out, these changes will be included in the May 2021 release of FilterCodes on Moodle.org.

Best regards,

Michael

**Comment by davefoord** [comment]
Hi Michael - I have tested this on a Moodle 3.10 and that is working as expected - which is great, but we cannot get the github code to update another moodle I support which is currently 3.8. I don't understand the technical side of things, but the host company cannot get it to work. My 3.8 moodle isn't urgent, I will be updating this in a few months time so will wait for the release in May before I use it on that one.

**Comment by michael-milette** [comment]
Hi @davefoord , thank you for testing and providing your positive feedback. I am not sure what to tell you about Moodle 3.8. I actually do a lot of my development in Moodle 3.8 right now including the development and fixing of this feature so I know it works. I just test in the other versions of Moodle. If they could provide you with more information on why they think it doesn't work, I might be able to offer more insight and troubleshooting steps.

I am going to close the ticket for now but, if it still doesn't work for you when released in May, feel free to re-open this ticket or create a new one.

Thanks again for your help.

Best regards,

Michael
