### ISSUE TITLE
Get question_id

### ISSUE THREAD

**Issue by signorettae** [michael-milette/moodle-filter_filtercodes#147]
Hello, 
I'm trying to get the question id in order to create a single question answer in quizzes (like here: https://moodle.org/mod/forum/discuss.php?d=391916). Can you please tell me how to do that?
Thank you in advance.

**Comment by michael-milette** [comment]
Hi @signorettae ,

There is a lot of discussion and many ideas on that page. Could you provide me with: 

- Step-by-step instructions on how to set-up a working example.
- Show me what information a FilterCode you would need to provide and where.
- An example of how you would use it.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @signorettae ,

As I haven't heard back from you in over 1.5 months, I am moving this issue to the backlog. We may get back to it in the future but, without additional information, we cannot place a focus on this at the moment. If you would like to hire us and make this a high priority, please contact us through our website at https://www.tngconsulting.ca .

Best regards,

Michael

**Comment by michael-milette** [comment]
Closing this issue due to insufficient information available to proceed with development.
