### ISSUE TITLE
Feature request: {sectionname}

### ISSUE THREAD

**Issue by brunohcury** [michael-milette/moodle-filter_filtercodes#156]
Hi Michael,
This plugin is awesome.
Can you tell me if I can insert a filter to get the name of the section an activity is in?
Something like {sectionname}?
Thank you so much!

![course-page](https://user-images.githubusercontent.com/25593136/123137602-a7520600-d443-11eb-84c5-3f4f5f96dbbd.png)
![page-2](https://user-images.githubusercontent.com/25593136/123137597-a620d900-d443-11eb-8ba5-17a46d3f05a1.PNG)

**Comment by michael-milette** [comment]
Hi @brunohcury ,

Thank you very much for submitting your feature request. The information you provided was very helpful.

You asked for it? You got it! The latest version of FilterCodes here on GitHub (v2.2.3) now includes a shiny new {sectionname} tag. I would appreciate it very much if you could try it out and let me know if it works for you.

If it works for you, I will include it in the next release of FilterCodes, which will be released around the same time as Moodle 4.0 in November 2021 (I only release there twice a year). However, you are more than welcome to continue using the version from GitHub until then.

Best regards,

Michael Milette

**Comment by brunohcury** [comment]
Fantastic Michael, amazing.

It met my expectations perfectly.
Thank you very much, for sure this is a plugin that must not be missing for those who use Moodle.

**Comment by michael-milette** [comment]
You are very welcome. :-)

I really appreciate hearing that you find you are finding it useful. Thank you for reaching out with your suggestion.

Best regards,

Michael

**Comment by brunohcury** [comment]
Hi Michael,

Using the same example mentioned above, I ask: Is there any filter to bring {instancename}?

**Comment by michael-milette** [comment]
Please open a new ticket for this feature request and provide an example of how you would use this. I do not understand what you mean by instance name.
