### ISSUE TITLE
Not working after my update to 3.11

### ISSUE THREAD

**Issue by fabiorcamargo** [michael-milette/moodle-filter_filtercodes#157]
Hello I updated my moodle to version 3.11 and I'm not able to make the plugin work, I installed it through the interface and manually, without success, when I put {} it doesn't make the filter.
But I don't understand what's wrong I have another installation, identical server and it's working properly.

**Comment by fabiorcamargo** [comment]
I managed to solve, actually the plugin is ok, it was disabled after the update even after reinstalling.
It was necessary to enable in site administration / plugin / filters / manage filters.
After enabling it worked perfectly, congratulations this plugin is essential.

**Comment by michael-milette** [comment]
Thank you @fabiorcamargo ,

I am glad to hear that you figured it out. It is really nice to hear from people like you who find FilterCodes really useful. It is comments like yours that makes all the effort I put into its development worthwhile. 

Best regards,

Michael
