### ISSUE TITLE
Feature request: Include non-editing teachers in {courseteachers} or create a new filter code

### ISSUE THREAD

**Issue by cam-howard** [michael-milette/moodle-filter_filtercodes#159]
Hi Michael,

I'm looking for a way to use FilterCodes to display the name(s) of non-editing teachers in the same way {courseteachers} displays the name(s) of teachers.

For my use case, it would suffice to have the same filter code list both teachers and non-editing teachers.

Other use cases may want to list those two separately so creating a new code for each role could be a better option to add that flexibility.

This is a terrific plugin! Thanks for all your work on it.

Cam

**Comment by michael-milette** [comment]
Hi @cam-howard ,

Thanks for the suggestion. Please try out the new {coursecontacts} tag. You can control who appears in the list by configuring Site Administration > Appearance > Courses > course contacts. There you can include any one or multiple roles defined in your instance of Moodle.

Please note that this feature is currently only available on GitHub and will be released in December around the same time as Moodle 4.0. It is backwards compatible of course.

If you could try it out and get back to me with your feedback (good or bad), it would be much appreciated.

Best regards,

Michael

**Comment by pierregb** [comment]
En que entorno se puede traer {courseteachers}?, pruebo con global $COURSE y no lo trae

In which environment can {courseteachers} be brought? I try with global $ COURSE and it doesn't bring it

**Comment by cam-howard** [comment]
Hi Michael,

The new {coursecontacts} tag is great! I appreciate the options for configuration -- which roles to include and whether the person's name should link to their email address, profile, or other options. The icons indicating the type of link are helpful.

It's doing exactly what I was looking for. It's a big time-saver and ensures the correct instructor and/or facilitator displays in several places in each course without having to make manual updates each time that information changes.

I really appreciate your work on this plugin and the addition of this feature. 

Thanks,
Cam

**Comment by michael-milette** [comment]
Hi @cam-howard ,

Thank you for your kind words. I really appreciated hearing from fans. And thank you very much for testing it out. This fix will be included in the forthcoming release of FilterCodes on Moodle.org.

Best regards,

Michael
