### ISSUE TITLE
{ifprofile_field_shortname} tag Conditional access based on user profile field doesn't work

### ISSUE THREAD

**Issue by davefoord** [michael-milette/moodle-filter_filtercodes#162]
Hi Michael - I have a scenario where I want to show content to people only if a certain custom user profile field is not blank. I did think I could use {ifprofile_field_shortname}{/ifprofile_field_shortname} but this doesn't appear to be working, so I am assuming this relates to custom course fields not custom user fields.

Is it possible to filter based on a custom user profile field?

**Comment by michael-milette** [comment]
Hi @davefoord ,

The  {ifprofile_field_shortname}{/ifprofile_field_shortname} tags are for the custom user profile fields.  I have update the documentation here on GitHub to make it clear.

I am not sure why it is not working for you if you replace "shortname" with the shortname of your custom user profile field.

Can you provide me with more details on what you are doing and in what type of course activity or resource?

Best regards,

Michael

**Comment by davefoord** [comment]
Thanks for the quick reply Michael.

here is a screen shot of what I have added - you will see that the filtercodes tags are displaying on the page (it is a chapter of a book). I have added a filter code displaying my name to confirm that the filter is enabled within the course

![image](https://user-images.githubusercontent.com/28855774/127290837-ef10e1db-5f86-4b76-a118-024db5810e07.png)

Here is the html code I have added:

<p>{ifprofile_field_L2CoachingVenue}</p>
<p>Some content</p>
<p>{/ifprofile_field_L2CoachingVenue}</p>
<p><strong>Your name is: <span style="color: #ff0000;">{fullname}</span></strong></p>

And here is the screenshot of the custom user profile field I am using:

![image](https://user-images.githubusercontent.com/28855774/127291215-8ea9850b-ce9c-4d63-b391-7616c507ddab.png)

What am I doing wrong?

**Comment by davefoord** [comment]
OK - so me adding the html code didn't work, as it has rendered it (as expected) so here is a screenshot of the code:

![image](https://user-images.githubusercontent.com/28855774/127291450-55aff447-1a47-4a60-a27c-b65f881570ab.png)

**Comment by michael-milette** [comment]
Which version of Moodle are you using?

**Comment by michael-milette** [comment]
Also, what type of field is L2CoachingVenue?

**Comment by michael-milette** [comment]
Hi @davefoord ,

Looks like there were two issues. One was that I had the "visible only" setting backwards. When checked, this setting will cause the tag to act as if the field value was empty or zero if the field was set to hidden.

The other issue, which prevented it from working at all, was a space that got accidently inserted into the source code (probably by my cat walking across the keyboard) about 2 weeks ago between the opening { and the if.

Thanks to you reporting this, the issue should be resolved, at least on GitHub for now. If you would be so kind, could you please give the latest version here on GitHub a try (usual master branch) and let me know if this solves your issue?

Best regards,

Michael

**Comment by davefoord** [comment]
Hi @michael-milette I am getting this updated on my Moodle tomorrow so will be able to test it then.

I don't think you need it now, but in case it is helpful, I am on Moodle 3.10.4 and the L2CoachingVenue is a 'text input' field.

**Comment by davefoord** [comment]
Hi @michael-milette - we have installed updated plugin onto the Moodle, and it is working now.

Thanks for fixing so quickly,

**Comment by michael-milette** [comment]
Hi @davefoord ,

You are welcome! Thank you for testing the fix and getting back to me.

This fix will be integrated into the next release version scheduled for November 2021, around the release of Moodle 4.0. Feel free to continue using the version here on GitHub. It always includes the newest features and latest bug fixes.

Best regards,

Michael
