### ISSUE TITLE
Feature Request: filtercode for custom name primary button

### ISSUE THREAD

**Issue by Brada65** [michael-milette/moodle-filter_filtercodes#165]
It would be great to have filter code for a primary button like "Continue" in the lessons.

Of course option of the custom name of the button will be much better (your idea).

As we already talked it should be like this:

{button https://google.ca}Continue{/button}

Thank you!

**Comment by michael-milette** [comment]
Hi @Brada65 ,

As requested, I have added the new {button URL}Label{/button} tag. Here are 3 examples:

- {button https://www.tngconsulting.ca}Go to TNG Consulting Inc.{/button}
- {button https://google.ca" target="_blank}Go to Google in a new window{/button}
- {button {wwwroot}/my}{getstring}myhome{/getstring}{/button}

The last one will create a button called "Dashboard", using the Moodle language strings, with a link to /my in your Moodle site, regardless of where Moodle is installed (root or subdirectory). The result will be (colour may vary depending on your theme):
![image](https://user-images.githubusercontent.com/3808579/132254431-a1f051d9-4a17-49b3-aa8c-776dc0b22cbe.png)

This new feature is currently only available in the version of FilterCodes available here on GitHub. This feature will be included in the next release of FilterCodes on Moodle.org around the same time as Moodle 4.0, currently expected in December 2021.

If you would be so kind, I would appreciate it very much if you could test the new {button} tag and let me know whether or not it works for you and meets your needs.

Best regards,

Michael

**Comment by Brada65** [comment]
Thank you Michael, on your quick response. Here are result on my local moodles first one is just bare 3.11 with your theme, and filtercodes.
![buttons](https://user-images.githubusercontent.com/22346041/132504531-8176b61c-fe80-4f85-be4b-ce8a4ab6bbe8.png)

Second one is my 3.9 with Adaptable theme and lot of other plugins, but same result.
![buttons2](https://user-images.githubusercontent.com/22346041/132504897-aee28465-5d81-4b97-b4d9-08c0f7d97944.png)

Based on last example "Dashboard" on both platforms, I think it is something in URL that is causing this.

Best regards,

Vladimir

**Comment by Brada65** [comment]
One more result from real situation, tag added to discussion forum description to lead to the next lesson page.
![buttons3](https://user-images.githubusercontent.com/22346041/132507655-2c992aad-da65-4502-93fd-4ed9d4322f69.png)

Resulted with this.
![buttons4](https://user-images.githubusercontent.com/22346041/132507683-02838d42-3396-48ed-8d1c-1ab1f5bb925a.png)

I hope this will be helpful too.

Best regards,

Vladimir

**Comment by Brada65** [comment]
You were 100% right.
If you unlink url in editor it is showing the button.

![unlinked_urls1](https://user-images.githubusercontent.com/22346041/132528944-cd7baf08-3565-4049-8037-78e52a613495.png)

It must be manually entered, first try was copy url and paste, the next one is manually entered (look at the button :)).

![manually_entered](https://user-images.githubusercontent.com/22346041/132531658-1bfd92e0-81e4-4ca0-901d-aa526d3d2863.png)

Great work!

Thank you again,

Vladimir

**Comment by michael-milette** [comment]
Thanks Vladimir. I should probably include that tip in the documentation :-)

**Comment by Brada65** [comment]
It helps also if order of filters are set in a certain way. "Filter Codes" need always to be before "Convert URLs into links and images"

![filters_order](https://user-images.githubusercontent.com/22346041/132564724-9c610adf-bc22-4af3-827a-ba4142171868.png)

It was my pleasure to work with you,

Vladimir

**Comment by michael-milette** [comment]
Thanks for the tip! I usually have FilterCodes near or at the top of the list of filters.

**Comment by michael-milette** [comment]
The documentation has been updated to include the suggestion of unlinking the URL in the WYSIWYG editor. See:
https://github.com/michael-milette/moodle-filter_filtercodes#why-does-the-button-tag-not-work

This feature will be published on Moodle.org around the time of the release of Moodle 4.0 expected in December 2021.

Thanks again for your help!

Michael
