### ISSUE TITLE
{now} filtercode not working with format

### ISSUE THREAD

**Issue by hengeb** [michael-milette/moodle-filter_filtercodes#168]
With my Moodle installation (Moodle 3.11.3, plugin version 2.2.4 (2021052505), PHP 7.4.22, timezone Europe/Berlin; unfortunately I have to possibility to change any of these for testing purposes) the {now} filter code only shows a correct result when there is no format argument included. In any other case the filter code will break the page.

**example:**

raw page content: "___ABC___ {now} ___DEF___ {now} ___GHI___ {now strftimetime} ___JKL___ {now strftimedate} ___MNO___ {now strftimedatetime} ___PQR___ {now} ___STU___"

is expected to be rendered as: "___ABC___ 22.09.21 ___DEF___ 22.09.21 ___GHI___ 10:29 ___JKL___ 22 September 2021 ___MNO___ 22 September 2021, 10:29 AM ___PQR___ 22.09.21 ___STU___"

What I get instead is: "___ABC___ 22.09.21 ___DEF___ 22.09.21 ___GHI___ 10:29 ___STU___"

Not only are some of the codes not showing, they also remove some of the contents that follow outside the code.

regards
Henrik

**Comment by michael-milette** [comment]
This is related to #166 .

**Comment by michael-milette** [comment]
Hi @hengeb ,

I think I have the issues with the date/time-related tags fixed. This includes the following tags:

- firstaccessdate
- coursestartdate
- courseenddate
- coursecompletiondate
- now

This fix addresses the issues described in #166 , #168 and #191 including cutting off of text and multiple instances of these tags not appearing or not being processed correctly.

The fix has been pushed to the code here on GitHub for now. If you have a chance, I would appreciate it very much if you would try it out and let me know if it works properly for you. If it does, I will include the fix in the upcoming release of FilterCodes on Moodle.org.

**Tip:** Type **{now}** manually in Moodle. Do not copy and paste your example from GitHub. Doing so often introduces extra HTML codes and/or characters which will prevent the tag from working.

Best regards,

Michael

**Comment by michael-milette** [comment]
I am closing this issue with the assumption that it is all working now as there has been no feedback over the past month. If there is a problem, please open a new issue and mention issue #168.

Best regards,

Michael
