### ISSUE TITLE
The {coursecontacts} tag should list anyone with a role enabled as a course contact

### ISSUE THREAD

**Issue by joostelshoff** [michael-milette/moodle-filter_filtercodes#192]
Currently, there's a bit of code for the {courseteachers} tag that only checks for users with a role assignment for roleid = 3, which is the default editingteacher role. This does not take into account that many organisations using Moodle have designed custom teaching roles that are listed as course contacts, but have a roleid that isn't 3.

I'd like to see this improved in a future version of the plugin, so it will list all users with a course contact role.

**Comment by michael-milette** [comment]
Hi @joostelshoff ,

What role are your "course contacts" based on?

Best regards,

Michael

**Comment by joostelshoff** [comment]
I'd have to look into that, but the usual archetype for the custom editing teacher role is 'editingteacher' (roleid = 3). We also come across category level roles involved in courses derived from the manager role, but these aren't considered course teachers / course contacts. 

The ideal improvement here would be to do the following (IMHO):

In the Site admin > Plugins > Filters > FilterCodes page, include a setting (multiselect) to select which roles to consider course teachers, analogously to how you'd select course contacts in Site admin > Appearance > Courses > 'coursecontact'.

**Comment by joostelshoff** [comment]
For me, that would work... and I would guess that also applies to every properly implemented Moodle instance, which is of course what we (you) are aiming for ;)

**Comment by michael-milette** [comment]
What if I rename the tag to {coursecontacts} and include anyone who meets the criteria set in Course Contacts page? That way I would not need a custom setting in FilterCodes. Please feel free to share your thoughts.

**Comment by joostelshoff** [comment]
Ooh! That would immediately solve the issue. The fewer customizable settings, the better ;).

**Comment by michael-milette** [comment]
Hi @joostelshoff ,

Please try out the new **{coursecontacts}** tag. As discussed, you should be able to control who appears in the list by configuring Site Administration > Appearance > Courses > course contacts. There you can include one or multiple roles defined in your instance of Moodle.

Please note that this feature is currently only available on GitHub and will be released in December around the same time as Moodle 4.0. It is backwards compatible of course.

If you could try it out and get back to me with your feedback (good or bad), it would be much appreciated.

Best regards,

Michael

**Comment by joostelshoff** [comment]
Hi Michael,

That looks awesome! I tested this, also with local role renames, and must say it does exactly what I was searching for... Unticking boxes in the Appearance > Courses > Course contacts bit automatically removes the deselected role from the list.

**Comment by michael-milette** [comment]
Thanks for the feedback. Glad to hear that it is meeting your needs.

Best regards,

Michael
