### ISSUE TITLE
{coursecontacts} Is it possible to at least remove blank lines?

### ISSUE THREAD

**Issue by Alexandre-Scherbyna** [michael-milette/moodle-filter_filtercodes#195]
Unfortunately, {coursecontacts} has the same formatting as {courseteachers}. The line feed before each name and one blank line after each name. Here is a screenshot: https://www.screenpresso.com/=6Z6Qe
Is it possible to at least remove blank lines?

**Comment by michael-milette** [comment]
Hi @Alexandre-Scherbyna ,

Please give the version 2.2.7 that I recently published here on GitHub a try. It should resolve your issue and adds a class called fc-coursecontacts which will enable you to customize the display using CSS.

This change is currently only available here on GitHub. If you could give it a try and get back to me, I would really appreciate it. If it works for you, it will be included in the next release of FilterCodes on Moodle.org, which will be coming out around the same time as Moodle 4.0.

Best regards,

Michael

**Comment by Alexandre-Scherbyna** [comment]
I have installed version 2.2.7. There the {coursecontacts} tag doesn't work: https://www.screenpresso.com/=Lwosb

**Comment by michael-milette** [comment]
Hi @Alexandre-Scherbyna ,

Where are you putting the {coursecontacts} tags? It only works within the context of a course. But even outside the course, it should still just remove the tag.

Also, what version of Moodle are you using exactly?

Please confirm that you have upgraded Moodle.

Please confirm that you have navigated to Site Administration > Notifications and completed the database update after upgrading the plugin.

I tried it:
![image](https://user-images.githubusercontent.com/3808579/144736371-587def35-8e2e-4a83-97c2-ce9b5fa013a1.png)

In a page:
![image](https://user-images.githubusercontent.com/3808579/144736411-a0200ed4-2455-4fb7-a90c-35a15283b9b3.png)

In a block:
![image](https://user-images.githubusercontent.com/3808579/144736394-e1d21548-d350-4b42-8048-0df91bd413a4.png)

In a label:
![image](https://user-images.githubusercontent.com/3808579/144737742-cacd9210-3e24-4364-b427-38e9f5f064d0.png)

I just uploaded a new version 2.2.8. However, the only changes I made were to fix the icons (were not appearing) and fixed the phone number fieldname.

Best regards,

Michael

**Comment by Alexandre-Scherbyna** [comment]
Hi Michael! 
Sorry, the tag was copied along with the span style. Here is the HTML code:

1111111{<span style="font-size: 0.9375rem;">coursecontacts</span>}22222222222{firstname}333333

I removed the span style and now the tag works. There are no empty lines! 
Thanks a lot!

I used versions 2.2.7 and 2.2.8. Moodle 3.11.

**Comment by michael-milette** [comment]
Glad to hear that you worked it out @Alexandre-Scherbyna . I appreciate you testing it out. I discovered the issue with the icons because of you. Thanks! :-)

Michael
