### ISSUE TITLE
Feature request: "Visibility" 

### ISSUE THREAD

**Issue by bfriesenvcc** [michael-milette/moodle-filter_filtercodes#196]
It would be awesome if there were a tag for course visibility. :-)
Love this plugin!

**Comment by michael-milette** [comment]
Interesting! Can you give me an example of how you would use this?

**Comment by bfriesenvcc** [comment]
Using FilterCodes, we've created a "sticky block" called, "Need Help?" This block expands to show useful links, but some of the most important things (in our opinion) are visible at the top. If there were a visibility tag, we would add the line "Course Visibility: HIDE" or "Course Visibility: SHOW." Something like that, anyway. :-) 

Hmm... now that I've written that out, I'm thinking it may be better to have conditional filters like {ifhidden}{/ifhidden} instead. 

Collapsed view:
<img width="171" alt="NeedHelp1" src="https://user-images.githubusercontent.com/8193384/149597486-ec178dcf-c448-4e9c-b6c9-97fa69ae24bd.PNG">

Expanded view:
<img width="162" alt="NeedHelp2" src="https://user-images.githubusercontent.com/8193384/149597517-f428255b-b41f-47a3-a409-fe2fd7d1d5b6.PNG">

**Comment by michael-milette** [comment]
Hi @bfriesenvcc ,

Why would you want to show the course visibility status to students? If the course visibility is set to hidden, students would not be able to access the course.

On a side note, if you don't mind, I am very curious on how you created the expandable sticky block using FilterCodes. Would you mind sharing?

Best regards,

Michael

**Comment by bfriesenvcc** [comment]
Sorry, Michael. I neglected to mention that we also use your filtercodes to show the students something else: 
![needhelpstudents](https://user-images.githubusercontent.com/8193384/149983030-ee125032-0862-4eea-9288-f67ddcb670dd.PNG)

The previous images are what course editors only will see. 

So, I created an HTML block on the front page of Moodle and set the  page contexts settings to "Display throughout the entire site."

I then went to edit the HTML within a random course, immediately changing Display on Page types setting to "Any type of course main page."

I then added the content of the block which contained all of the code and made great use of your filtercodes.
![needhelpcode](https://user-images.githubusercontent.com/8193384/149984158-4163e323-b916-41b8-af31-0ad35c262382.PNG)

Previously, I used permissions to show a sticky block only to editors and NOTHING to students. However, somewhere around Moodle 3.2 (I think) the permissions trick stopped working for sticky blocks and only worked for regular blocks. Then I got the idea of using your filtercodes and it saved us.

**Comment by michael-milette** [comment]
Hi @bfriesenvcc ,

Nice! Thank you.

I am still not clear on why you would you want to show the course visibility status. It sounds to me like all you are really looking for is a set of {ifnotvisible}{/ifnotvisible} tags or something like that which would enable you to display a warning when the course is not set to "show".

Michael

**Comment by bfriesenvcc** [comment]
No, the student view doesn't show the course visibility. They only see the suggestion to report issues to the instructors. Only the course editors see the view that would include the visibility. And, yes, I think the if/ifnot tags would do the job nicely because I could word it any way that I chose.

**Comment by michael-milette** [comment]
Thanks for your feedback. Last thing before I do this. Do you understand that this tag will only work in a course? It will not work outside of the course or in course listings.

**Comment by bfriesenvcc** [comment]
Yes, that makes sense to me and that's how I plan to use it. :-)

**Comment by michael-milette** [comment]
ok, give me a few minutes. I am testing it now.

**Comment by michael-milette** [comment]
Hi @bfriesenvcc ,

Just pulled it out of the oven! Looks ready to me. If you have a few minutes, I would really appreciate it if you could test the new tag for me and let me know if it meets your needs. Here is an example of how it could be used:

{ifnotvisible}Warning: Course visibility is set to Hide.{/ifnotvisible}

Please note that this new tag is only available here on GitHub at the moment. It will be released on Moodle.org around the same time as Moodle 4.0.

Best regards,

Michael Milette

**Comment by bfriesenvcc** [comment]
Michael, you are truly amazing! I will try to test before I leave today. I'm pretty sure I can get that done.

**Comment by bfriesenvcc** [comment]
It seems that I cannot use nested conditionals.

The screenshot shows my block on the right and, on the same page, a label resource in the content area. The ifnotvisible is working as expected in the label, but not in my block. I suspect it's because I'm trying to put the {ifnotvisible} inside the {ifminassistant} code:

{ifminassistant}This is for course editors only. {ifnotvisible}Warning: Course is set to Hide!{/ifnotvisible}{/ifminassistant}
![ifnotvisible](https://user-images.githubusercontent.com/8193384/150036471-197147f6-c8c9-4bf6-8320-2a7688376589.PNG)

**Comment by michael-milette** [comment]
Hi @bfriesenvcc ,

It works fine for me exactly as you typed it. Here is the code that I put into an HTML block:

    {details}{summary}More information{/summary}
    Contact us for help.
    {ifminassistant}This is for course editors only. {ifnotvisible}Warning: Course is set to Hide!{/ifnotvisible}{/ifminassistant}
    {/details}

Some people have mentioned that extra codes get pasted into the editor when they copy from GitHub and paste in Moodle's Atto editor. Take a look at the HTML view to see if some unexpected characters might have accidentally been added to your text.

Best regards,

Michael

**Comment by bfriesenvcc** [comment]
OK, I've done quite a bit of playing around, and pulling out of hair, but I've solved the issue IN MY CASE.

Basically, long story short, I believe it was related to the use of {courseenddate} when the end date was disabled for that particular course. 

Any of the following methods solved the problem:
1. Adding an end date to the course (easy solution, but we have issues forcing end dates)
2. Adding a line break in the SOURCE code before the {_ifnotvisible_} (also easy but took forever to realize this)
3. Moving the {_ifnotvisible_}{/_ifnotvisible_} above the course end date.
4. Adding a paragraph break after the {courseenddate} entry and (for some reason) removing the class="" from the <p> tag.

To reproduce the first two methods, mentioned above:

1. Paste the following source code into an HTML block of a course with no end date:
```
<p>Your Course ID is <strong>{courseid}</strong><br> Start date: {coursestartdate}<br>End date: {courseenddate}<br>{ifnotvisible}<strong>Warning: Course visibility is set to Hide</strong>.{/ifnotvisible}<br>{ifeditmode}editing is turned on.{/ifeditmode}
</p>
```
2. Notice that neither the _ifnotvisible_ nor the _ifeditmode_ warnings are showing.(image1)
3. Go enable the end date of the course and save.
4. Notice that both _ifnotvisible_ and _ifeditmode_ warnings are showing.(image2)
5. Disable the end date, again.
6. Notice that, once again, neither the _ifnotvisible_ nor the _ifeditmode_ warnings are showing.(image1)
7. Edit the course code of the block, simply adding a line break before {_ifnotvisible_} (images 3 and 4)
8. Notice that both the _ifnotvisible_ and _ifeditmode_ warnings are showing again.

Image1:
<img width="188" alt="Image1" src="https://user-images.githubusercontent.com/8193384/150204112-0e38f1ad-5555-4105-87ae-d7026a65e5ec.PNG">

Image2:
<img width="186" alt="Image2" src="https://user-images.githubusercontent.com/8193384/150204125-40cd4f93-a98c-4ee8-80a3-3fb2f882f083.PNG">

Image3:
<img width="472" alt="Image3" src="https://user-images.githubusercontent.com/8193384/150204138-31d41c3d-8a52-4cc5-8687-57fecfb24a24.PNG">

Image4:
<img width="468" alt="Image4" src="https://user-images.githubusercontent.com/8193384/150204150-52654666-08b8-4bff-9ea3-6cbed3fe18bd.PNG">

**Comment by michael-milette** [comment]
A couple of questions:

1. What version of Moodle are you using?
2. Are you using NGINX?

**Comment by bfriesenvcc** [comment]
We're using Moodle 3.9.11, but I had to Google NGINX, so I'm going to say "no."

**Comment by jb-fol** [comment]
This is a really nice filtercode! Just sharing an example for others to see if interested:

![Screenshot 2022-01-25 at 22 51 58](https://user-images.githubusercontent.com/15047124/151073254-acb312fb-7333-41d9-9519-4b3a1c29f047.png)
