### ISSUE TITLE
Add support for locally assigned (on module/activity) custom roles to {ifcustomrole} tag

### ISSUE THREAD

**Issue by Richardvi** [michael-milette/moodle-filter_filtercodes#198]
See for more info here: https://moodle.org/mod/forum/discuss.php?d=359252#p1738300

**Comment by Richardvi** [comment]
@michael-milette is there anything I can do to help you with this feature?

**Comment by Richardvi** [comment]
@michael-milette If you want funding for this, please contact me.

**Comment by Richardvi** [comment]
Offer still stands :)

**Comment by michael-milette** [comment]
Hi @Richardvi , 

Please send me a message via my website at https://www.tngconsulting.ca/contact and we will make arrangements to talk soon.

Best regards,

Michael

**Comment by Richardvi** [comment]
Did that 😊

Hope to speak with you soon.

Van: Michael Milette ***@***.***>
Verzonden: donderdag 29 juni 2023 19:28
Aan: michael-milette/moodle-filter_filtercodes ***@***.***>
CC: Richard van Iwaarden ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [michael-milette/moodle-filter_filtercodes] Add support for locally assigned (on module/activity) custom roles to {ifcustomrole} tag (Issue #198)


Hi @Richardvi<https://github.com/Richardvi> ,

Please send me a message via my website at https://www.tngconsulting.ca/contact and we will make arrangements to talk soon.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi Richard,Sorry for the delay in getting back to you. Would you be available to meet virtually this week? I think I am about 6 hours behind your local time here in Ottawa Canada.Best regards,Michael
-------- Original message --------From: Richardvi ***@***.***> Date: 2023-07-03  12:58 p.m.  (GMT-05:00) To: michael-milette/moodle-filter_filtercodes ***@***.***> Cc: Michael Milette ***@***.***>, Mention ***@***.***> Subject: Re: [michael-milette/moodle-filter_filtercodes] Add support for
  locally assigned (on module/activity) custom roles to {ifcustomrole} tag
  (Issue #198) 
Did that 😊



Hope to speak with you soon.



Van: Michael Milette ***@***.***>

Verzonden: donderdag 29 juni 2023 19:28

Aan: michael-milette/moodle-filter_filtercodes ***@***.***>

CC: Richard van Iwaarden ***@***.***>; Mention ***@***.***>

Onderwerp: Re: [michael-milette/moodle-filter_filtercodes] Add support for locally assigned (on module/activity) custom roles to {ifcustomrole} tag (Issue #198)





Hi @Richardvi<https://github.com/Richardvi> ,



Please send me a message via my website at https://www.tngconsulting.ca/contact and we will make arrangements to talk soon.



Best regards,



Michael

**Comment by Richardvi** [comment]
Hi Michael,

Yes, we could meet this week. Can you plan something in your morning so it will be my afternoon 😊

I couldn’t find your mail address to send a MS Teams invitation. All mail addresses seem to be getting censored, but still let’s try again: my mail address is ***@***.******@***.***>

Hope to hear from you!

Richard.

Van: Michael Milette ***@***.***>
Verzonden: maandag 31 juli 2023 20:52
Aan: michael-milette/moodle-filter_filtercodes ***@***.***>
CC: Richard van Iwaarden ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [michael-milette/moodle-filter_filtercodes] Add support for locally assigned (on module/activity) custom roles to {ifcustomrole} tag (Issue #198)

Hi Richard,Sorry for the delay in getting back to you. Would you be available to meet virtually this week? I think I am about 6 hours behind your local time here in Ottawa Canada.Best regards,Michael
-------- Original message --------From: Richardvi ***@***.***<mailto:***@***.***>> Date: 2023-07-03 12:58 p.m. (GMT-05:00) To: michael-milette/moodle-filter_filtercodes ***@***.***<mailto:***@***.***>> Cc: Michael Milette ***@***.***<mailto:***@***.***>>, Mention ***@***.***<mailto:***@***.***>> Subject: Re: [michael-milette/moodle-filter_filtercodes] Add support for
locally assigned (on module/activity) custom roles to {ifcustomrole} tag
(Issue #198)
Did that 😊



Hope to speak with you soon.



Van: Michael Milette ***@***.***<mailto:***@***.***>>

Verzonden: donderdag 29 juni 2023 19:28

Aan: michael-milette/moodle-filter_filtercodes ***@***.***<mailto:***@***.***>>

CC: Richard van Iwaarden ***@***.***<mailto:***@***.***>>; Mention ***@***.***<mailto:***@***.***>>

Onderwerp: Re: [michael-milette/moodle-filter_filtercodes] Add support for locally assigned (on module/activity) custom roles to {ifcustomrole} tag (Issue #198)





Hi @Richardvi<https://github.com/Richardvi> ,



Please send me a message via my website at https://www.tngconsulting.ca/contact and we will make arrangements to talk soon.



Best regards,



Michael

**Comment by michael-milette** [comment]
Hi @Richardvi ,

It has been a while since I last heard from you so I will assume that this is all working correctly. This fix will be included in the upcoming release on moodle.org within the next few weeks.

Thanks again for the Feature Request and yours and HZ University of Applied Sciences' financial support! I really appreciate it.

Best regards,

Michael

**Comment by Richardvi** [comment]
Hi Michael,

Also a lot of thanks from this side for your work. I’m in Italy the upcoming two weeks and will have an update run end of October. We will update to Moodle 4.3 as well.

Have a great weekend,

Richard.

Van: Michael Milette ***@***.***>
Verzonden: donderdag 28 september 2023 20:31
Aan: michael-milette/moodle-filter_filtercodes ***@***.***>
CC: Richard van Iwaarden ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [michael-milette/moodle-filter_filtercodes] Add support for locally assigned (on module/activity) custom roles to {ifcustomrole} tag (Issue #198)


Hi @Richardvi<https://github.com/Richardvi> ,

It has been a while since I last heard from you so I will assume that this is all working correctly. This fix will be included in the upcoming release on moodle.org within the next few weeks.

Thanks again for the Feature Request and yours and HZ University of Applied Sciences' financial support! I really appreciate it.

Best regards,

Michael
