### ISSUE TITLE
Why is it not using getremoteaddr()

### ISSUE THREAD

**Issue by mudrd8mz** [michael-milette/moodle-filter_filtercodes#2]
Moodle provides a core function `getremoteaddr()`. Why does the filter implement its own method `filter_filtercodes::getuserip()` ?

**Comment by michael-milette** [comment]
I've been using my own IP detection routine for several years. Unfortunately I don't recall why anymore. I seem to recall there being a bug for a while with Moodle's getremoteaddr() function. Since I can't think of the reason right now, I've switched it to use the getremoteaddr() function instead.
