### ISSUE TITLE
{wwwroot} tag issue for students (when using Log In As)

### ISSUE THREAD

**Issue by brunohcury** [michael-milette/moodle-filter_filtercodes#205]
Hello Michael,
I'm using the following link inside atto:
<a href="{wwwroot}/course/view.php?id={courseid}#section-{sectionid}">

For my admin user, the link is working correctly, but in the student's view the filtercodes cannot interpret the tags, see the images below.
Can you help me
Thank you very much

![view-admin](https://user-images.githubusercontent.com/25593136/161287544-3ade6816-160f-4e05-9fcf-89dc96aa4895.PNG)
![view-student](https://user-images.githubusercontent.com/25593136/161287715-7f0d8198-dfa0-4523-9964-8bb59422dce8.PNG)

**Comment by brunohcury** [comment]
Hello Michael,
Thanks for the quick response.
I believe this is not so.
Because as an administrator it works normally, only as a student the {wwwroot} filter cannot be applied.

**Comment by michael-milette** [comment]
Can you tell me exactly where you are putting the link to the page? I need enough information in order to be able to reproduce the problem on my own sites.

**Comment by brunohcury** [comment]
I am inserting the link inside the resource page in the atto editor.

![link-atto](https://user-images.githubusercontent.com/25593136/161328239-34a9f95d-1117-4791-be53-729864dbc865.PNG)
![preview](https://user-images.githubusercontent.com/25593136/161328256-568c009f-7454-4bf7-b497-cfdb2f5b2faa.PNG)

**Comment by michael-milette** [comment]
Hi @brunohcury ,

I put your exact HTML code into a page and it worked perfectly.

    <div style="text-align: left;" class="attostylebox-solid atto-stylesbox-solid-blue" data-uw-styling-context="true"><span style="font-size: x-large;" data-uw-styling-context="true"><span class="" style="font-size: x-large;" data-uw-styling-context="true">1 -- Collelacao entre marketing e logistica</span></span>
        <p style="float:right; " data-uw-styling-context="true"><a href="{wwwroot}/course/view.php?id={courseid}#section-{sectionid}" class="btn btn-outline" style="font-size:14px; color:#fff; text-decoration:none;" data-uw-styling-context="true">[fa-undo] VOLTAR</a></p>
    </div>

Unfortunately, it looks like this is an issue specific to your Moodle installation. Let me know if I can be of service to you in this matter.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @brunohcury 

I noticed that you are also using another filter, the FontAwesome plugin, which is not working either. I can see the [fa-undo] tag.

_**Did you know?**_ FilterCodes also supports FontAwesome icons.

In your example using the FontAwesome plugin:
[fa-undo]

In FilterCodes it would be:
{fa fa-undo}

Best regards,

Michael

**Comment by brunohcury** [comment]
Hello Michael,
Good to know that FilterCodes can also be used with FontAwesome.
About the HTML code, here in my Moodle it works normally in the admin user, but when I am logged in as a student, the link does not work, when I move the mouse over the link the student sees {wwwroot}, and the tag {fa fa-undo} it works perfectly.
I still haven't figured out what it could be. Did you test the link as a student?
Thanks in advance for your immense help.

**Comment by brunohcury** [comment]
Michael,

My FontAwesome is working correctly, the print sent shows the tag in page editing mode in the atto editor, but when saved to display the content, it is normal.

**Comment by michael-milette** [comment]
Yes, I tested it both as a student and as an administrator. It worked perfectly as designed.

I am not sure what more to tell you. I can see in your screenshots that the other tags in the URL are working so obviously FilterCodes is correctly configured. The only times I have ever seen this happen, NGINX was involved. I can only suggest that you contact your server administrator and check with them.

The last time this happened (last year), I sent the following link to the server administrator (I did not have access to the server config).

https://docs.moodle.org/en/Nginx

Two hours later, he emailed me back and said that the problem was solved and that it was related to nginx being used as a proxy server in front of the server. Unfortunately he never answered my request to find out what it was that he changed.

Hope this helps.

Best regards,

Michael

**Comment by brunohcury** [comment]
Hello Michael,
Thanks for your prompt help.
Find out the problem.
This is happening when "access as student", this way shows the {wwwroot} tag in the url, however, when accessing directly with the student's username and password, the problem is not displayed.
Will it be a bug?
Thanks in advance for your help

**Comment by michael-milette** [comment]
Hi @brunohcury ,

"Log in as" has a bug in Moodle. I have experienced it before where Moodle rewrites some HTML during output. It is not clear to me why Moodle processes HTML differently when using that feature. 

For more information, see:

https://tracker.moodle.org/browse/MDL-65372

Please vote for this issue if you agree that it needs to be fixed.

I am not sure if there is anything more I can do from a filter point of view.

It is good to be aware of this. Good catch and thank you for sharing your findings.

Best regards,

Michael

**Comment by michael-milette** [comment]
I just added a note in the FilterCodes documentation for issues relating to both the use of nginx and log in as. Thank you!
