### ISSUE TITLE
Course participant count includes non students

### ISSUE THREAD

**Issue by emmarichardson** [michael-milette/moodle-filter_filtercodes#212]
Is there a way to limit the course participant count to students - currently it includes all roles...

**Comment by michael-milette** [comment]
Not yet. Something to consider for the future though.

**Comment by garetharnott** [comment]
I noticed this too - it would be nice to have filters for {coursestudentcount} {coursenon-editingcount} {coursefacilitatorcount} I large courses this can be a 'nice', but not a personal 'high-priority' feature.

regards
Gareth

**Comment by michael-milette** [comment]
Hi @emmarichardson 

Great news! The new **{coursecount students}** tag that you requested, which shows just the number of students enrolled in the course, has been added to FilterCodes.

At the moment, this new feature is only available here on GitHub. Could you please try it out and let me know if it works for you? If it does, this feature will be included in the upcoming release on moodle.org around the launch of Moodle 4.1 in about a month.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
Hi @garetharnott ,

Thanks for the suggestions. If you would like to see a {coursecount non-editing} and {coursecount facilitator}, please create new separate tickets for each of them and be sure to include real-life use cases.

Best regards,

Michael

**Comment by garetharnott** [comment]
Thanks for this @michael-milette - I think the student one is the most important/useful, so I'm not going to add requests for the others now - my main motivation though is that I am hoping you get to the {ifingrouping} tag :)

**Comment by emmarichardson** [comment]
That's wonderful - thank you so much!

**Comment by michael-milette** [comment]
HI @emmarichardson ,

This new tag is now also available on Moodle.org. Thanks again for your suggestion!

Best regards,

Michael
