### ISSUE TITLE
{coursecontacts} link doesn't work properly

### ISSUE THREAD

**Issue by Urpokarhu1** [michael-milette/moodle-filter_filtercodes#214]
Hello,

{coursecontacts} makes a link pointing to teachers phonenumber tel: -link (if teacher's phone number is empty)

![image](https://user-images.githubusercontent.com/53904029/168560621-ad26c6c5-94bb-42f3-a665-5f848068e11e.png)

When you add phonenumber to teachers Moodle profile the link dissappears.

![image](https://user-images.githubusercontent.com/53904029/168560693-11e69a66-6376-4741-83f7-0ca721c21ae1.png)

![image](https://user-images.githubusercontent.com/53904029/168560755-84ba02f8-cd31-49cf-8750-7b8cc8ce3574.png)

Can you add a setting that lets you specify what information is used in the link? Email address would make a lot more sense

- Tested with
- Moodle 3.9.12
- filter_filtercodes 2.3.0

**Comment by michael-milette** [comment]
Hi @Urpokarhu1 ,

There is already a setting for the link type in the FilerCodes settings plugin.

![image](https://user-images.githubusercontent.com/3808579/168697943-4cd94516-cfaf-4101-b8fd-52cb234a5cde.png)

The options include:

- **None**: No link
- **Email**: Contact's email address as set in their profile.
- **Message**: Link to the contact's Moodle messaging.
- **Profile**: Link to the contact's profile page.
- **Phone**: Link to the telephone number in the contact's profile "Phone" field.

Does this meet your needs? The limitation is that you can only set one type of link for all contacts listed.

As for the **tel:** appearing when you do not specify a phone number, I am not sure why that is happening for you. Unfortunately, I am unable to understand what it says in your screenshot. Also, what theme are you using? It is possible that this **tel:** is being injected by your theme's CSS or JavaScript if it detects that a field is a telephone number.

Best regards,

Michael

**Comment by Urpokarhu1** [comment]
Hello,

This fullfills my need, thanks.
