### ISSUE TITLE
Increasing maximum number of {global_...} tags

### ISSUE THREAD

**Issue by andrewrowatt-masseyuni** [michael-milette/moodle-filter_filtercodes#217]
Hi Michael & team,

Fantastic plugin!!  We are making a lot of use of it and consequently are very close to hitting the globaltagcount limit of 20.  Are we able to increase that safely - to say 50??

Advice appreciated!.

Regards, 
  Andrew

Massey University

**Comment by michael-milette** [comment]
Hi @andrewrowatt-masseyuni ,

Thank you for your kind words. I don't think it would be a problem. The limit of 20 was chosen to try and limit the impact on the system.

Do you mind if I ask how you are using the {global} tags that you need so many?

Best regards,

Michael

**Comment by andrewrowatt-masseyuni** [comment]
Thanks for the advice @michael-milette.  We have a lot of standard text in our University course template and using FilterCodes seemed a good option.  We have around 3,000 courses that are rolled over each year and often have minimal maintenance, so to update text once is hugely useful.

**Comment by andrewrowatt-masseyuni** [comment]
Sure, our course template has up to 10 general sections, each with at least one explainer note, most have a separate recommendations note as well.  We also use global tags for site-wide notices (e.g. COVID related).  Thanks,  Andrew

**Comment by michael-milette** [comment]
Hi @andrewrowatt-masseyuni ,

As requested, I increased the maximum number of {global_...} tags to 50. The change is currently only available here on GitHub and is ready for testing. I would really appreciate it if you be so kind as to test it and let me know if it works for you.

If it does, the change will be included in the next release of FilterCodes on Moodle.org.

Best regards,

Michael Milette

**Comment by andrewrowatt-masseyuni** [comment]
Thank you @michael-milette!

**Comment by michael-milette** [comment]
Hi @andrewrowatt-masseyuni ,

This is now also available on Moodle.org. Thanks again for your suggestion!

Best regards,

Michael
