### ISSUE TITLE
Feature request: Support other tags within {chart progressbar x Title text}

### ISSUE THREAD

**Issue by philipsiwinski** [michael-milette/moodle-filter_filtercodes#218]
Hi @michael-milette, many thanks for contributing this great plugin.

I tried to use the new {chart progressbar x Title text} tag which works very well.
However, I was wondering if it would be possible to add support for other tags within this tag.

I imagine something like that:
{chart progressbar {profile_field_percentagenumber} {profile_field_titletext}}

What do you think?

Thanks a lot :)

**Comment by michael-milette** [comment]
Hi @philipsiwinski , it depends. is {profile_field_...} the only tag that you would need?

Can you describe to me what you are trying to do and how you get your values into the profile fields?

**Comment by philipsiwinski** [comment]
Thank you @michael-milette, yes I would only need this kind of tags {profile_field_...}.
In relation with the other issue I opened, I'm trying to display a progress bar (to show the global progress accross multiple courses for learners who are not enroled in the same courses) in a text block on the default dashboard for all users. In order to have the progress bar display each learner's own progress, I imagine storing these progress values in custom profile fields. For each learner, the values of these profile fields will be set and the regularly updated by an external system via web services or by local custom plugins. Did I explain the scenario well enough? Thanks

**Comment by michael-milette** [comment]
Thanks for the information @philipsiwinski . I will see what I can do for you.

**Comment by michael-milette** [comment]
Hi @philipsiwinski ,

Thank you again for contributing your suggestion.

You asked for it? You got it! You can now use the {profile_field_...} tag inside the {chart} tag. Please be sure that you have numbers only in the profile field, without the % symbol beside it. Valid range is from 0 to 100.

This enhancement is currently available here on GitHub. If you would be so kind, I would really appreciate it if you could try it out as I would like to include this in the upcoming release of FilterCodes on Moodle.org within the next few days.

Best regards,

Michael
