### ISSUE TITLE
Feature request: {ifingrouping}

### ISSUE THREAD

**Issue by garetharnott** [michael-milette/moodle-filter_filtercodes#220]
Hi Michael,

An update and feature request - filtercodes is up and running on our site which I am so excited about. The group code {mygroups} you sorted out works a charm, thanks. I am also going to use the {ifingroup} filter as well, but see that there is no {ifingrouping} version which would be useful. I tried the grouping ID just in case, but it doesn't work. Is this easy to do?

kind regards
Gareth

**Comment by michael-milette** [comment]
Hi @garetharnott 

Thanks for your feedback. I've never used grouping but it certainly sounds like a good idea. Could you give me a real life example of how you would use an {ifingrouping} tag?

Best regards,

Michael

**Comment by garetharnott** [comment]
Hi @michael-milette,

Thank you for your quick response. Groupings are groups of groups. There are many uses for these, but as one example in my course I have groupings called 'Tuesday' and 'Thursday' for practical groups. So there are two types of tags that would be useful.

1.  [ifingrouping} would allow you to have specific text aimed at a student in that grouping, e.g. [ifingrouping groupingid}You have your pracs and tuts on a Thursday{/ifingrouping}
2. {mygroupings} which would allow you to have something like: You are in {mygroup} which has pracs and tuts on {mygroupings} afternoons. I would set up the {mygroupings} tag in the same way as the {mygroups} that you recently did.

Is that enough information? There are many scenarios, but they all have the same underlying idea.
kind regards 
Gareth

**Comment by michael-milette** [comment]
Hi @garetharnott ,

Thank you for the examples.

However it is not clear to me why you are using groupings instead of groups in your example. Could you elaborate on that a little?

**Comment by garetharnott** [comment]
Hi Michael,

Groupings help when it comes to group assessments/assignments. If a student is in a small group and a large group (that is essentially a group of groups) then group submission settings get all chaotic. A grouping is just more flexible in so many scenarios. E.g. if you need to move a student from one group to another, they will automatically be assigned to the correct grouping (so no need to manually change them twice). In small courses this would not be too much of an issue, but when you have a course like mine of 1200 students, thus 250 groups of 5 students each, groupings becomes an essential tool to manage everything. A prac grouping might have 16 groups, so when students need to shift from one prac day to another, you only need to change the group they are in as the prac grouping will automatically adjust based on the group they are in.

Does that help?

kind regards
Gareth

**Comment by garetharnott** [comment]
@michael-milette I don't mean to add another message to your inbox, but gosh filtercodes has really revolutionised my Moodle experience. The {ifingrouping xxx} code is still on my wish-list but I see there are many other wishes out there. I am so sorry I can't help, even with testing due to my institution's policies, but this plugin is amazing.

regards
Gareth

**Comment by michael-milette** [comment]
HI @garetharnott ,

@28Smiles recently contributed a solution for your request. There are now 3 new grouping tags available:

- {ifingrouping id|idnumber}...{/ifingrouping}
- {ifnotingrouping id|idnumber}...{/ifnotingrouping}
- {mygroupings}

These new tags are currently only available here on GitHub in the master branch. If you would be kind and would have the time, could you please try them out and let me know if it works for you. If there are no issues, this will be included in the next release of FilterCodes on moodle.org.

Best regards,

Michael

**Comment by michael-milette** [comment]
Closing this issue as it has been resolved in FilterCodes release 2.6.0.
