### ISSUE TITLE
{mygroups} and {ifingroup}

### ISSUE THREAD

**Issue by garetharnott** [michael-milette/moodle-filter_filtercodes#221]
Hi Michael,

I noticed a weird thing - the {ifingroup xx}{/ifingroup} tags would not work on a page (in this case a book) where I also used the {mygroups] tag. At first I found it weird that the {ifingroup} tag was not working, when it worked fine on another page. Then I copied the text directly from the other page and it still didn't work. Then I decided to delete the {mygroups} tag and then {ifingroup} worked. I also had another tag {participantcount} which worked and didn't affect anything whether it was there or not.

Sorry - I know bugs can be a bug - but I thought I should report it.

regards
Gareth

**Comment by michael-milette** [comment]
Hi @garetharnott ,

Don't apologize. I appreciate learning about bugs and fix them rather than have people get frustrated and give up saying that FilterCodes doesn't work.

I will look into this but need your help in reproducing the problem. Could you please tell me exactly where you place the tags and provide me with a sample of text that includes the tags (order may matter) that does not work?

Also, when it does not work, does it simply display the tag or does it get replaced with incorrect information?

Best regards,

Michael

**Comment by michael-milette** [comment]
Found the bug. You were right, I had a variable called $mygroups that was used for both tags. One clobbered the other if they were both used. An error was displayed when debugging mode was enabled to the DEVELOPER level:

    Warning: Invalid argument supplied for foreach() in filter/filtercodes/filter.php on line 3053

I should have that fixed shortly.

Michael

**Comment by michael-milette** [comment]
Hi @garetharnott ,

I believe the issue has been resolved. If you would be so kind, I would appreciate it very much if you would install the latest version here on GitHub and let me know if it resolves the issue for you.

If it works, I will push the fixed version to Moodle.org shortly after.

Best regards,

Michael

**Comment by garetharnott** [comment]
Hi @michael-milette 

Well done and thanks! I don't have the capability as I am not admin, but I have contacted our support staff and asked if they can test on the development site. I'll let you know when I get feedback.

regards
Gareth

**Comment by garetharnott** [comment]
Hi Michael - I have been able to test the update and it works (a big shout-out to our IT guys who pulled some strings). 

many thanks!
Gareth

**Comment by michael-milette** [comment]
Thanks for letting me know. That is good news. I will push the update out on Moodle.org in the next few days.
