### ISSUE TITLE
Filters are not applied to messages within a course

### ISSUE THREAD

**Issue by atrolex** [michael-milette/moodle-filter_filtercodes#223]
Hi again @michael-milette  :)

I am trying to send message from a course to selected users:
![image](https://user-images.githubusercontent.com/33658481/173220616-84a8b697-a3c2-41f2-8167-ddda4816f1bf.png)

Email comes as:
![image](https://user-images.githubusercontent.com/33658481/173220179-13f46210-324e-44da-a102-4d4800d73dcd.png)

If a send a message via site administration / user / bulk user actions everything works fine.

**Comment by michael-milette** [comment]
Hi @atrolex ,

Unfortunately that is a limitation of Moodle, not FilterCodes.

FilterCodes is just a filter which gets applied in Moodle as long as Moodle passes content through the filters. In this case, unfortunately, it does not.

The only way to enable that functionality would be to develop a patch to the Moodle core code. Then, you will need to remember to re-apply the patch each time you update or upgrade Moodle.

You can develop the patch yourself or you can hire someone like me to do it for you. If you are interested in hiring me, please contact me through my website at https://www.tngconsulting.ca/contact to make arrangements.

Best regards,

Michael Milette

**Comment by atrolex** [comment]
Thank you @michael-milette ! we have solved it via a workaround. Now we do not need any variables.
