### ISSUE TITLE
Max Courses on frontpage.

### ISSUE THREAD

**Issue by behoof** [michael-milette/moodle-filter_filtercodes#231]
L.s.

Mighty fine plugin!

Tip for the documentation: the {coursecards} are related to the front page field frontpagecourselimit.
 I was wondered why not all courses were shown. This was the cause ;-)

Bert van der Hooft.

**Comment by michael-milette** [comment]
Hi @behoof , 

So happy to hear that you find this plugin useful.

Thank you for bringing this up. You are not the first to mention this. I will be sure to add this information to the documentation in the README.md file.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
Hi @behoof , the documentation in the README.md file has been updated.

Thanks for reporting this issue!
