### ISSUE TITLE
Feature Request: Turn off tags or limit tags to specific roles

### ISSUE THREAD

**Issue by a-kempka** [michael-milette/moodle-filter_filtercodes#239]
### Prerequisites

- [X] I am requesting the new feature to the correct repository.
- [X] I checked the latest version on GitHub and the [README.md](../blob/master/README.md) documentation to ensure that this functionality does not already exist.
- [X] I searched to make sure that this feature has not already been requested.
- [X] I have, or I know someone who has, the ability and willingness to test the new feature on a Moodle LMS-based site.
- [X] I agree to submit one feature request per issue ticket (do not submit multiple requests in one issue ticket).
- [X] I understand that development and support is provided by volunteer(s) and that all final implementation decisions are up TNG Consulting Inc.

### Feature Request - The User Story

Thanks for the great plugin!

As a Moodle Administrator I want to be able to have a granular control which FilterCodes tags can be used under which circumstances. It would be great to:
- be able to turn specific tags off for evereyone. Especially those that can lead to security problems, e.g. showing infos about the system, about user details (username)
- be able to choose which role can use which tag
 - at the moment students could spam forums with alert boxes containing the username of a person for phishing etc.
 - at the moment students can spam coursecards in a forum. On an installation with many courses this may lead to a bad user experience (slow loading of courses, load on the server)

### Planning on submitting a solution in a pull request (PR)?

No

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Duplicate of #227
