### ISSUE TITLE
Correct documentation for {supportpage} tag.

### ISSUE THREAD

**Issue by dinism** [michael-milette/moodle-filter_filtercodes#240]
### Prerequisites

- [X] I am requesting the new feature to the correct repository.
- [X] I checked the latest version on GitHub and the [README.md](../blob/master/README.md) documentation to ensure that this functionality does not already exist.
- [X] I searched to make sure that this feature has not already been requested.
- [ ] I have, or I know someone who has, the ability and willingness to test the new feature on a Moodle LMS-based site.
- [X] I agree to submit one feature request per issue ticket (do not submit multiple requests in one issue ticket).
- [X] I understand that development and support is provided by volunteer(s) and that all final implementation decisions are up TNG Consulting Inc.

### Feature Request - The User Story

In your file "README.md", in section System Information you have:
. {supporturl} : Support page as seen on Site Administration > Server > Support contact.

but the tag is **{supportpage}**.
https://github.com/michael-milette/moodle-filter_filtercodes/blob/64bddb9275e4de1b89040da03b4564dbbaffe548/filter.php#L1192

### Planning on submitting a solution in a pull request (PR)?

Maybe

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by dinism** [comment]
https://github.com/michael-milette/moodle-filter_filtercodes/blob/64bddb9275e4de1b89040da03b4564dbbaffe548/README.md?plain=1#L136

**Comment by michael-milette** [comment]
Hi @dinism ,

Thank you very much for reporting this issue. I really appreciate it. I have updated the README.md file with the correct information. This change is currently only available here on GitHub but will also be included in the upcoming release on Moodle.org around the launch of Moodle 4.1.

Best regards,

Michael
