### ISSUE TITLE
Feature Request: Unenrol tag

### ISSUE THREAD

**Issue by behoof** [michael-milette/moodle-filter_filtercodes#242]
### Prerequisites

- [X] I am requesting the new feature to the correct repository.
- [X] I checked the latest version on GitHub and the [README.md](../blob/master/README.md) documentation to ensure that this functionality does not already exist.
- [X] I searched to make sure that this feature has not already been requested.
- [X] I have, or I know someone who has, the ability and willingness to test the new feature on a Moodle LMS-based site.
- [X] I agree to submit one feature request per issue ticket (do not submit multiple requests in one issue ticket).
- [X] I understand that development and support is provided by volunteer(s) and that all final implementation decisions are up TNG Consulting Inc.

### Feature Request - The User Story

The unenroll link in Moodle is hidden and many users can't find it easily. I would like to have a filtercode for unenrol.

### Planning on submitting a solution in a pull request (PR)?

No

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @behoof ,

You don't need a filtercode tag for this. Here are three options for you:

1. Just add the following link in your course page:

https://yourmoodlesite.edu/enrol/manual/unenrolself.php?enrolid=1

This will unenroll you from the current course that you are viewing.

2. If you want to turn it into a button, you can use the following filtercodes:

{button {wwwroot}/enrol/manual/unenrolself.php?enrolid=1}Unenrol me from this course{/button}

3. If you want to just have a tag and not have to specify the URL, create a {global_unenrol} tag in the FilterCodes setting and put whatever code you want in it. Then you can simply insert the {global_unenrol} tag in your course page to have it show up.

The result will be something like this:
![image](https://user-images.githubusercontent.com/3808579/205503252-9ae4a608-7246-4367-8cc9-b4dec6a496ca.png)

Hope you find this helpful.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
This tag is now also available on Moodle.org. Thanks again for your suggestion!
