### ISSUE TITLE
Feature Request: Filter available courses on homepage based on user profile fields.

### ISSUE THREAD

**Issue by PhredMau** [michael-milette/moodle-filter_filtercodes#243]
### Prerequisites

- [X] I am requesting the new feature to the correct repository.
- [X] I checked the latest version on GitHub and the [README.md](../blob/master/README.md) documentation to ensure that this functionality does not already exist.
- [X] I searched to make sure that this feature has not already been requested.
- [X] I have, or I know someone who has, the ability and willingness to test the new feature on a Moodle LMS-based site.
- [X] I agree to submit one feature request per issue ticket (do not submit multiple requests in one issue ticket).
- [X] I understand that development and support is provided by volunteer(s) and that all final implementation decisions are up TNG Consulting Inc.

### Feature Request - The User Story

As  a student, i want to be able to view only list of available courses from my city/region
As an admin I want to be able to display courses based on students profile field.

### Planning on submitting a solution in a pull request (PR)?

Yes

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @PhredMau ,

Thanks for submitting your proposal.

1. It looks like you are proposing two new features. If this is the case, could you please edit your proposal and split them into two separate tickets?
2. Please add more detail on why you want to do this and how you plan to approach the issue.

Looking forward to working with you on this.

Best regards,

Michael Milette
