### ISSUE TITLE
Feature Request: Lists instead of Cards

### ISSUE THREAD

**Issue by boxxcar1** [michael-milette/moodle-filter_filtercodes#250]
### Prerequisites

- [X] I am requesting the new feature to the correct repository.
- [X] I checked the latest version on GitHub and the [README.md](../blob/master/README.md) documentation to ensure that this functionality does not already exist.
- [X] I searched to make sure that this feature has not already been requested.
- [X] I have, or I know someone who has, the ability and willingness to test the new feature on a Moodle LMS-based site.
- [X] I agree to submit one feature request per issue ticket (do not submit multiple requests in one issue ticket).
- [X] I understand that development and support is provided by volunteer(s) and that all final implementation decisions are up TNG Consulting Inc.

### Feature Request - The User Story

Currently there are a few Filtercodes that display information as cards (i.e Coursecards) - my request would be to have the same information displayed as a list instead of cards. The reasoning behind this is a list can display much more information without scrolling than the cards do. I purpose maybe a Courselist filter? Would be even better if the list could display related information like the category/description/course image etc

### Screenshots / Mock-ups

![concept - all courses list](https://user-images.githubusercontent.com/122877400/212883602-19318395-5d6c-41ef-a37a-7bc08c53324e.png)

### Planning on submitting a solution in a pull request (PR)?

Yes

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
HI @boxxcar1 ,

Thank you for your suggestion. In FilterCodes, the best I could offer to do for you would be to have a setting which would switch the cards instead into a table format containing the course name and category or something like that.

As I a sure you already know, Moodle's native course listing is already in a table format so I sense that it is really the filter functionality that you are after. If that is the case, this would really be more of a theme and/or block customization to override Moodle's own course listing format. Also, the list of fields and filters in the course listing would most likely be unique to your particular requirements.

If you are interested in hiring me to provide you with custom development services for Moodle LMS, please contact me through my website at https://tngconsulting.ca/contact.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
Hi @boxxcar1 ,

Take a look at the latest version of FilterCodes here on GitHub. It includes a list option which displays the courses in a table. Fields include course name, category and description. However, it does not feature any filtering. To choose that format, you will need to configure it in the FilterCodes settings.

Best regards,

Michael

**Comment by boxxcar1** [comment]
Thanks Michael! I'll give it a try - what would be required to add a filter/search to the list option?

**Comment by michael-milette** [comment]
Hi @boxxcar1,

At the moment, the table is responsive and column widths are automatically adjusted by Bootstrap. I have not tried it but you might be able to manipulate column widths using CSS. I made sure each of the columns had classes.

To add a filter/search feature would require more development to implement [datatables](https://datatables.net/).

Best regards,

Michael
