### ISSUE TITLE
Feature Request: coursestartdate based on course ID

### ISSUE THREAD

**Issue by krisslaber** [michael-milette/moodle-filter_filtercodes#251]
### Prerequisites

- [X] I am requesting the new feature to the correct repository.
- [X] I checked the latest version on GitHub and the [README.md](../blob/master/README.md) documentation to ensure that this functionality does not already exist.
- [X] I searched to make sure that this feature has not already been requested.
- [X] I have, or I know someone who has, the ability and willingness to test the new feature on a Moodle LMS-based site.
- [X] I agree to submit one feature request per issue ticket (do not submit multiple requests in one issue ticket).
- [X] I understand that development and support is provided by volunteer(s) and that all final implementation decisions are up TNG Consulting Inc.

### Feature Request - The User Story

**Basis for request:** {coursename ID} and {coursesummary ID} can pull information from a different course based on course ID. 

**Request:** Add ID to {coursestartdate}

**Use Case:** Marketing other courses on a similar course page; posting course time in description. Course pages with schedule in label. This option would be valuable with learner bases in multiple time zones.

### Alterative you have considered

My SQL commands
Every variation of current {coursestartdate}
Nesting {Coursestartdate} with {Coursename ID} in different configuations.

### Planning on submitting a solution in a pull request (PR)?

No

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @krisslaber,

Thank you for the suggestion. The {coursestartdate} tag can now have an optional course id parameter. Note that if you specify both the date/time format and course id parameter, the id parameter must appear after the date/time format, not before.

A few examples of valid syntax:

- {coursestartdate}
- {coursestartdate 3}
- {coursestartdate strftimedate}
- {coursestartdate strftimedate 3}
- {coursestartdate strftimedate 9999} --> will result in 31 December 1969 if the course id does not exist.

This is invalid:

- {coursestartdate 3 strftimedate}

Please note that this feature is currently only included with the version of FilterCodes available here on GitHub. If you would be so kind, I would be really thankful if you would be so kind as to try it out and let me know if works for you.

Best regards,

Michael Milette

**Comment by krisslaber** [comment]
It works perfectly inside any course page. I can retrieve the start date
for a different course page and it displays as expected.
The start date does not display outside of a course page such as on the
home page or in the course description. It continues to display "Not yet
started."

In course description
[image: image.png]
On course page
[image: image.png]

**Comment by michael-milette** [comment]
Hi @krisslaber ,

Thank you for testing and reporting the new issue. Unfortunately, your images did not come through however, I was able to reproduce the issue and found a few lines of old code that I forgot to remove. Should be all good now. Could you please try it again with the latest version here on GitHub?

Best regards,

Michael

**Comment by krisslaber** [comment]
Perfection! We have a world-wide learner base and this functionality is a
game-changer. Thank you so much for taking the time to update your
wonderful plugin!

**Comment by michael-milette** [comment]
Hi @krisslaber ,

Thank you for testing it again. Glad to hear that it is working for you.

Best regards,

Michael
