### ISSUE TITLE
Feature Request:  {activityid} - See {coursemoduleid}

### ISSUE THREAD

**Issue by lxd1979** [michael-milette/moodle-filter_filtercodes#256]
### Prerequisites

- [X] I am requesting the new feature to the correct repository.
- [X] I checked the latest version on GitHub and the [README.md](../blob/master/README.md) documentation to ensure that this functionality does not already exist.
- [X] I searched to make sure that this feature has not already been requested.
- [X] I have, or I know someone who has, the ability and willingness to test the new feature on a Moodle LMS-based site.
- [X] I agree to submit one feature request per issue ticket (do not submit multiple requests in one issue ticket).
- [X] I understand that development and support is provided by volunteer(s) and that all final implementation decisions are up TNG Consulting Inc.

### Feature Request - The User Story

Hi Michael

Thank you for this plugin, it is is superb.

I've been using the filters below to manage instructions for students based on their state of completion within an activity.
{ifactivitycompleted id}{/ifactivitycompleted} 
{ifnotactivitycompleted id}{/ifnotactivitycompleted} 

It would really help if the id could be pulled from the current activity rather than manually entering it. This would also reduce the effort associated with editing the ids in restored courses. Therefore I propose a new {activityid} that can be used in conjunction with those exisiting filter codes.

Thanks

### Alterative you have considered

I've tried playing around with the {scrape} filter but to no avail.

### Planning on submitting a solution in a pull request (PR)?

Yes

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @lxd1979 ,

Thank you for your suggestion of a new {activityid} tag. However, that functionality currently exists in FilterCodes since version 2.2 released in May 2021. The tag is called %7Bcoursemoduleid%7D. The curly braces are escaped because it was originally intended for use in a URL. Note that this tag only works in an activity.

I also just added a {coursemoduleid} tag with the curly brackets. If you would rather use that version, download the latest version available here on GitHub and please let me know if it works for you. Either way, the curly braces version will be included in the next release of FilterCodes.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @lxd1979 ,

Got it! I should be able to fix that. Will let you know as soon as it is ready again for testing.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @lxd1979 ,

Great news! You can now embed any of the following tags including the "coursemoduleid" tag that you requested:

- {courseid} and %7Bcourseid%7D
- {coursemoduleid} and %7Bcoursecontextid%7D
- {coursecontextid} and %7Bcoursecontextid%7D
- {coursemoduleid} and %7Bcoursemoduleid%7D

In your case, you can now do something like this:

    {ifactivitycompleted {coursemoduleid}}You're done!{/ifactivitycompleted}{ifnotactivitycompleted {coursemoduleid}}You're not done yet!{/ifnotactivitycompleted}

This change is currently only available in the version of FilterCodes here on GitHub. I would be thankful if you would be so kind as to try it out and let me know if it works for you. If it does, this change will be included in the next release of FilterCodes.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @lxd1979 ,

As it has been almost 2 months since I last heard from you, I will assume that this is all working correctly. This will be included in the upcoming release on moodle.org within the next few weeks.

Thanks again for the Feature Request.

Best regards,

Michael
