### ISSUE TITLE
Bug: Filtering is not occurring for Questionnaire's 'Advanced Settings'

### ISSUE THREAD

**Issue by Kevin-Hipwell** [michael-milette/moodle-filter_filtercodes#259]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [ ] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

Filtering is not occurring for Questionnaire activity's 'Advanced Settings' tab 'Additional Info' setting.

### What do you think should have happened?

I expected to see {firstname} being replaced with 'Admin' for Additional Info' setting.

### Steps to reproduce

* Enable and setup the filtercodes plugin.
* Download and install the latest Questionnaire plugin
* Create a Questionnaire Activity
* On the 'Description' setting add some tags ( example: {firstname} )
* Save and Display.
* The tag will display the users first name
* Now click the 'Advanced settings' tab
* On the 'Additional Info' setting add some tags ( example: {firstname} )
* Save and Display
* Now click the 'Questions' tab
* Add a question
* If you want add a tag to the 'Question Text' setting ( example: {firstname} )
* Go back to the 'Questionnaire' tab
* Click the 'Answer the questions...' button.
* Note that the tag has been replaced for the 'Description' setting, and the 'Question Text' setting, but not the 'Additional Info' setting.
![Selection_1864](https://github.com/michael-milette/moodle-filter_filtercodes/assets/23482064/2d4e36e9-0768-472f-b9a3-4fa5345c331f)

### Moodle version

Moodle 4.1.3 (Build: 20230424)

### Installed Moodle UI Language packs.

- [X] English only
- [ ] One or more other languages/regional dialects (specify below)
- [ ] Other

### System information

Client Device type: (Desktop)
Client Operating System: (Linux)
Client Web Browser: (Chrome)
Server Operating System: (Linux)
Server Webserver: (Apache)
Server PHP: (7.4.3)

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
HI @Kevin-Hipwell ,

Thank you for taking the time to report this issue. This issue not only affects FilterCodes but any plain text tags including multi-language tags like Multi-language Content (v2) found at https://moodle.org/plugins/filter_multilang2. It would therefore be really help many people in addition to yourself to get this fixed.

However, this is not an issue with the FilterCodes plugin but with the Questionnaire plugin. I recommend that you contact the developer of the Questionnaire plugin, Mike Churchward, and submit a request to have the output of that field pass through Moodle filters. You can find a link to the bug tracker for the Questionnaire plugin by going to https://moodle.org/plugins/mod_questionnaire and clicking on the "Bug Tracker" link.

I am sure he already knows about it and that this is just a small oversight but it may be helpful to point him to the Moodle Output API documentation at https://docs.moodle.org/dev/Output_functions, specifically the format_text() and format_string() functions. Moodle filters only work if content is passed though these functions as the content is being displayed.

If Mike Churchward doesn't have time to work on this right now and you are in a hurry to get the Questionnaire plugin fixed, contact me for paid support through my website at https://www.tngconsulting.ca.

I am closing this ticket for now as there is nothing more that I can do. If the problem persists after Mike fixes the Questionnaire plugin, please feel free to re-open this ticket and I will be happy to work on this further with you.

Best regards,

Michael Milette
