### ISSUE TITLE
Feature Request:  {courseimage} within the HTML editor

### ISSUE THREAD

**Issue by brunohcury** [michael-milette/moodle-filter_filtercodes#261]
### Prerequisites

- [X] I am requesting the new feature to the correct repository.
- [X] I checked the latest version on GitHub and the [README.md](../blob/master/README.md) documentation to ensure that this functionality does not already exist.
- [X] I searched to make sure that this feature has not already been requested.
- [X] I have, or I know someone who has, the ability and willingness to test the new feature on a Moodle LMS-based site.
- [X] I agree to submit one feature request per issue ticket (do not submit multiple requests in one issue ticket).
- [X] I understand that development and support is provided by volunteer(s) and that all final implementation decisions are up TNG Consulting Inc.

### Feature Request - The User Story

Hello Michael,

Is there a way to use the {courseimage} tag within atto's HTML editor?
My idea is to insert an HTML block in the course with the background course cover image as in the attached example.

Thank you very much

Att
Bruno Cury

![html](https://github.com/michael-milette/moodle-filter_filtercodes/assets/25593136/15eef644-1d25-43da-9d08-4ec7ebe1a293)

### Planning on submitting a solution in a pull request (PR)?

Yes

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @brunohcury ,

Thank you for your suggestion. 

I created a new "{courseimage-url}" tag for you. This should enable you to use it in CSS as a background image by adding something like the following in the source code view of the editor:

    <div style="background-image: url('{courseimage-url');">
        
    </div>

The new tag is currently only available here on GitHub. I would be thankful if you would be so kind as to try it and let me know if it works for you. If it meets your needs, I will include the new tag in the next release on Moodle.org.

Best regards,

Michael Milette

**Comment by brunohcury** [comment]
Hello Michael,
It is perfect!
I have no words to thank you.
Thank you very much
![capa](https://github.com/michael-milette/moodle-filter_filtercodes/assets/25593136/465e204f-0cc5-4e26-b0c5-9284e9442c98)

**Comment by michael-milette** [comment]
You're very welcome @brunohcury . Looks very nice. Would you mind sharing your HTML and styles that you used in order to achieve this?

**Comment by brunohcury** [comment]
Yes of course!

<div style="background-image:linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(52,74,113,0.22032563025210083) 84%), url(&quot;{courseimage-url}&quot;); background-size: cover; min-width: 100%; margin-top: 5px;">

{coursename}
{mygroups}

{firstname}, seu progresso no curso está {courseprogress}

{courseprogressbar} 

{coursecontacts}
</div>

I remain available
Att.
Bruno Cury

**Comment by brunohcury** [comment]
![contatos](https://github.com/michael-milette/moodle-filter_filtercodes/assets/25593136/15f85863-7705-49c6-a92d-dd58c0e5c121)

**Comment by brunohcury** [comment]
Thank you very much!

**Comment by michael-milette** [comment]
Thank you for sharing @brunohcury .

Tip: You can probably put all that code in a FilterCodes Global tag. That way, you would just need to add one tag to your course. And, if you ever need to change it in all your courses, you would simply need to change it in one place.

Best regards,

Michael
