### ISSUE TITLE
Feature Request: {listgroups} and {listgroups students:active}

### ISSUE THREAD

**Issue by brunohcury** [michael-milette/moodle-filter_filtercodes#265]
### Prerequisites

- [X] I am requesting the new feature to the correct repository.
- [X] I checked the latest version on GitHub and the [README.md](../blob/master/README.md) documentation to ensure that this functionality does not already exist.
- [X] I searched to make sure that this feature has not already been requested.
- [X] I have, or I know someone who has, the ability and willingness to test the new feature on a Moodle LMS-based site.
- [X] I agree to submit one feature request per issue ticket (do not submit multiple requests in one issue ticket).
- [X] I understand that development and support is provided by volunteer(s) and that all final implementation decisions are up TNG Consulting Inc.

### Feature Request - The User Story

**Hello Michael,**
Once again I want to thank you for your effort in offering so many features to the Moodle community through your Plugin.
Thank you very much
I would like to know if there is already a tag that brings me the list of groups created and the total number of active subscribers in each one of them?
For example:
Only in the view of the teacher or course manager, use the tag **{listgroups students:active}** and it displays the following information

Pharmacy: 20
Biology: 30

Or use the {**listgroups}** tag to only list groups for that course:
Group 1
Group 2
Group 3

Thanks in advance for reading my message

Att
bruno

### Planning on submitting a solution in a pull request (PR)?

Yes

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @brunohcury ,

Thanks again for the suggestion. Could you please explain to me why and how you would actually use this?

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @brunohcury ,

It sounds to me like what you need is more of a report or am I misunderstanding you?

Best regards,

Michael Milette

**Comment by brunohcury** [comment]
Hello Michael,
Thank you for your return.
We will not necessarily use this information only for reports, but to make it easier for coordinators to read when they access Moodle and see this information in an HTML block of groups (classes) and active students.
We will easily have this data on the course screen of created groups and active students in each group (which Moodle does not allow us to do quickly today).
Thank you very much

**Comment by michael-milette** [comment]
Hi @brunohcury ,

I don't know. I am on the fence with this one. It sounds to me like this is a very specific use case and that a 'Groups List' block which provides the functionality you are asking for would make more sense.

Would this be useful to anyone else?

Michael

**Comment by brunohcury** [comment]
Hello Michael, good morning
Thank you for your return.
I didn't know there was a plugin for this task. In a search in the Moodle plugin repository I saw this one: https://moodle.org/plugins/block_groups

However, it shows exactly the number of members of each course and disregards suspended users.
It would be nice if we could choose whether we want to list all students or only active students in each group.
Anyway, I want to thank you for your help.

Bruno Cury

**Comment by brunohcury** [comment]
Michael,
I did a test and realized that the suspended students were left with "No group" so your idea perfectly solved what I needed.
Thank you very much

**Comment by michael-milette** [comment]
Thanks for sharing your findings @brunohcury . Much appreciated.

Best regards,

Michael
