### ISSUE TITLE
Bug: PHP 8 Deprecation 

### ISSUE THREAD

**Issue by susyzan** [michael-milette/moodle-filter_filtercodes#269]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [X] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

I am getting a risky test and the following deprecation notices when running unit tests (PHP 8.1.21, PHPUnit 9.5.27, Moodle 4.1.4):

`PHP Deprecated:  trim(): Passing null to parameter # 1 ($string) of type string is deprecated in /var/www/html/filter/filtercodes/tests/filter_test.php on line 143

PHP Deprecated:  trim(): Passing null to parameter # 1 ($string) of type string is deprecated in /var/www/html/filter/filtercodes/filter.php on line 1094`

### What do you think should have happened?

I expected the unit tests to run successfully

### Steps to reproduce

1. Ensure the unit test environment is initialised
2. From the cli run the unit tests (vendor/bin/phpunit --testsuite filter_filtercodes_testsuite)
3. See deprecation notices in the console and the risky test result

### Screenshots

![image](https://github.com/michael-milette/moodle-filter_filtercodes/assets/17571719/e153cb27-4e6c-4baa-9b80-13e38949ff0e)

### Moodle version

4.1.4

### Installed Moodle UI Language packs.

- [ ] English only
- [ ] One or more other languages/regional dialects (specify below)
- [ ] Other

### System information

PHP 8.1.21 
PHPUnit 9.5.27

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @susyzan ,

I am aware of that issue. It was due to a change with PHP 8.1.

The issue should already be fixed if you try the version of FilterCodes available here on GitHub.

Please let me know if it works better for you. I will be releasing a new version on Moodle.org within the next few weeks.

Best regards,

Michael Milette

**Comment by susyzan** [comment]
Hi @michael-milette,

Thank you for letting me know. 

I am probably looking at the wrong branch, but I don't seem to be able to find a fix for this. I created a PR just in case. Please feel free to ignore this if there is a fix already and sorry about the confusion.

Kind regards,
Susanna

**Comment by michael-milette** [comment]
Hi Susanna,

You are absolutely right. I went through all of my plugins fixing those trims but it looks like I missed that one. Thank you for submitting the PR. It has been integrated here on GitHub and will be included in all future releases of FilterCodes.

Let me know if it gives you any more trouble.

Best regards,

Michael

**Comment by susyzan** [comment]
Hi @michael-milette,

That's great. Thank you so much for maintaining this plugin.

Kind regards,
Susanna
