### ISSUE TITLE
Feature Request:  {participantslist} of current course

### ISSUE THREAD

**Issue by juancarlos-galdos** [michael-milette/moodle-filter_filtercodes#277]
### Prerequisites

- [X] I am requesting the new feature to the correct repository.
- [X] I checked the latest version on GitHub and the [README.md](../blob/master/README.md) documentation to ensure that this functionality does not already exist.
- [X] I searched to make sure that this feature has not already been requested.
- [X] I have, or I know someone who has, the ability and willingness to test the new feature on a Moodle LMS-based site.
- [X] I agree to submit one feature request per issue ticket (do not submit multiple requests in one issue ticket).
- [X] I understand that development and support is provided by volunteer(s) and that all final implementation decisions are up TNG Consulting Inc.

### Feature Request - The User Story

Hello,

It should be great to view all the participants in the course just using something like this: {participantslist}

I saw someone who asked for groups and active users, but for us is a list of participants enough.  It could be like {coursecontacts} but with the participants instead.

Thank you in advance.

### Planning on submitting a solution in a pull request (PR)?

Yes

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @juancarlos-galdos ,

Moodle already has a setting for who you want to include in the list of contacts. As a site administrator, just navigate to **Site Administration > Appearances > Courses** and select the roles of the people that you want to consider a course contact. 
<img width="245" alt="image" src="https://github.com/michael-milette/moodle-filter_filtercodes/assets/3808579/ff613e1c-551b-438b-9341-2ef4c8eb1325">

This controls who will be listed when you use the {coursecontacts} tag. Note that this is a global setting.

Hope you find this helpful.

Best regards,

Michael

**Comment by juancarlos-galdos** [comment]
That great. Thank you very much for the information and sorry for my ignorance.

**Comment by michael-milette** [comment]
You're welcome @juancarlos-galdos . No need to apologize.  Glad that I could help. 🙂
