### ISSUE TITLE
Bug: Tag is left behind when using in Custom Menu Items

### ISSUE THREAD

**Issue by sahinakkaya** [michael-milette/moodle-filter_filtercodes#280]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [ ] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

This might be same as #278 but I am reporting it anyway to make us understand the situation better. When I use `{ifminmanager}{/ifminmanager}` in Custom Menu Items (Site Administration -> Appearance -> Theme Settings -> Custom Menu Items), the navbar is not correctly populated. If I am logged in as manager, the link will be something like `<moodle-url>/<actual-endpoint>{/ifminmanager}` If I am not logged in it will not even rendered correctly

### What do you think should have happened?

I expected the link to be rendered correctly in all situations and go to the correct location when clicked.

### Steps to reproduce

1. Go to Site Administration -> Appearance -> Theme Settings -> Custom Menu Items
2. Add a custom menu item like: `{ifminmanager}My Custom Link|/my/courses{/ifminmanager}`
3. Save changes
4. Custom link should be visible at the top but it will render incorrectly and/or the link will be wrong.

### Logged in as Manager, the link is incorrect:
![resim](https://github.com/michael-milette/moodle-filter_filtercodes/assets/32161460/dd6f8adb-381e-4a6a-80fe-a23aa2dce6d4)

### Logged out. The link is incorrect and the menu item is not rendered correctly
<img width="741" alt="resim" src="https://github.com/michael-milette/moodle-filter_filtercodes/assets/32161460/64faca1e-b0a3-4a63-b7d9-7f56bbcb2087">

### Moodle version

Moodle 4.2.3+ (Build: 20231020)

### Installed Moodle UI Language packs.

- [X] English only
- [ ] One or more other languages/regional dialects (specify below)
- [ ] Other

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Sorry for the delay in following up with you. I could not reproduce this issue.

Best regards,

Michael

**Comment by sahinakkaya** [comment]
It was my fault, the answer was in README. I missed it because there was more than one section about custom menus.

**Comment by michael-milette** [comment]
Hi @sahinakkaya ,

Good point. Perhaps I should consider merging them to make it easier to find information. Thank you for the feedback.

Best regards,

Michael
