### ISSUE TITLE
Bug: Course Summary does not appear for {coursecards} or {coursecards ID#} tags in List layout's Description column

### ISSUE THREAD

**Issue by jprovasnik** [michael-milette/moodle-filter_filtercodes#292]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [ ] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

I am using the 2.4.3 version of Filtercodes on both Moodle Workplace 4.1 and Workplace 4.3 - I am not able to see any Course Summary data in the Description column when I use the {coursecards} tag with list layout selected in the admin interface. This information does appear once switching to Horizontal layout in the admin interface. 

### What do you think should have happened?

When I add {coursecards} or {coursecards 86} in a label on a Custom Page, Course page topic, or on the Dashboard I expected to see the text entered in a course's Course Summary field (in course settings) to appear in the description column. When I inspect the code in my browser, the TD cell is entirely empty. This information does populate when switching the admin settings to Horizontal View.

Course Description (aka Summary) appears in Horizontal View:
![Horizontal View](https://github.com/michael-milette/moodle-filter_filtercodes/assets/44345287/cb1ab14f-b2e2-4de0-88c4-7006ad42f052)

Course Description (aka Summary) does not appear in List View:
![List View](https://github.com/michael-milette/moodle-filter_filtercodes/assets/44345287/ce89ce81-3f1e-4f43-a81f-195712baf8be)

### Steps to reproduce

1. Login as Admin and on the Filter Codes Admin settings page, set Course cards layout to "Horizontal"
2. Go to the Dashboard, or a Custom Page if in Moodle Workplace, and add two labels
3. In one label paste {coursecards} and save
4. Paste {coursecards 86} into the other label -- but swap 86 with any other Moodle category ID that contains courses in which some courses have some text populated in the Course Summary field.
5. Save and confirm a list of courses is visible.
6. Also confirm that descriptions are populated for courses that contain them.
7. Return to the Filter codes Admin settings page and set Course cards layout to "List"
8. Return to the Dashboard or Custom page and confirm that the list of courses is still visible. 
9. Confirm whether not course descriptions are populated into the Description column for courses that contain them.

### Screenshots

![Course Cards Layout](https://github.com/michael-milette/moodle-filter_filtercodes/assets/44345287/206c944f-1400-4334-94e4-2533d4522732)

![filtercode](https://github.com/michael-milette/moodle-filter_filtercodes/assets/44345287/874cd7df-2f3a-4539-b186-f2ecf25f0c83)

![Horizontal View](https://github.com/michael-milette/moodle-filter_filtercodes/assets/44345287/470b6dc3-df65-489c-a07d-97db6b434abe)

![List View](https://github.com/michael-milette/moodle-filter_filtercodes/assets/44345287/109add0b-bdc2-41b1-96af-676dbbfdfef0)

### Moodle version

4.3.2

### Installed Moodle UI Language packs.

- [ ] English only
- [X] One or more other languages/regional dialects (specify below)
- [ ] Other

### If other language(s), please specify

en, en_us, es, fr, pt_br, ru, uk, ar, zh_cn

### Workaround

I use CSS to hid the third TH column to hide the entire Description column at this time.

### Additional information

I understand this is Moodle Workplace and that support here may be limited but wanted to report this in case it's also happening on Non-Workplace.

### System information

Client Device type: (e.g. Desktop, iPhone or iPad, Android phone or tablet, Other - specify)
Client Operating System: (e.g. Windows, Linux, Mac OS, Android, iOS, Other - specify)
Client Web Browser: (e.g. Chrome, Edge, Firefox, Safari, Safe Exam Browser, Moodle Mobile App)
Server Operating System: (e.g. Windows, Linux, Mac OS, Other - specify)
Server Webserver: (e.g. Apache, Nginx, IIS, Other - specify)
Server PHP: (e.g. 7.3, 7.4, 8.x, Other - specify)

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @jprovasnik ,

Fortunately, this was also a bug in Moodle LMS, not just in Moodle Workplace. The issue should be resolved in FilterCodes release 2.6. Don't forget to remove your CSS for the third column :-)

Best regards,

Michael Milette
