### ISSUE TITLE
Bug: {sesskey} is not resolved

### ISSUE THREAD

**Issue by Bjoern-Ge** [michael-milette/moodle-filter_filtercodes#295]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [X] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

I tryed to use the code {sesskey} in moodle-html. 
It was then shown as {sesskey} in the test.

### What do you think should have happened?

I expected that {sesskey} is replaced by the actual value. Other codes worked at the same spot.

### Steps to reproduce

1. Login as admin
2. Go to a course
3. Add a text field with the text {sesskey}
4. See {sesskey} instead of the key.

### Screenshots

![grafik](https://github.com/michael-milette/moodle-filter_filtercodes/assets/93242256/5922f25f-4643-4e50-90f5-48153ec49ede)

![grafik](https://github.com/michael-milette/moodle-filter_filtercodes/assets/93242256/c8e38bf1-ea04-4d31-a82b-7e19a25608e1)

### Moodle version

4.1

### Installed Moodle UI Language packs.

- [ ] English only
- [X] One or more other languages/regional dialects (specify below)
- [ ] Other

### If other language(s), please specify

en, de, de_du, uk

### System information

Client Device type: Laptop
Client Operating System: Win11
Client Web Browser: Firefox
Server Operating System: Debian
Server Webserver: nginx
Server PHP:8.0

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @Bjoern-Ge ,

Is sesskey enabled in the FilterCodes settings?

Are filters enabled in your course?

Are you sure that you checked for a solutiom the README.md file?

Best regards,

Michael

**Comment by Bjoern-Ge** [comment]
Hi @michael-milette ,
thanks for your fast replay. 
It wasn't enabled in the settings. Now it works.
Best regards,
Björn
