### ISSUE TITLE
Bug: ifingroup ID does not work

### ISSUE THREAD

**Issue by olemde** [michael-milette/moodle-filter_filtercodes#297]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [X] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

Hi Michael.
i can not make the {ifingroup ID} running and tried many options. Could you please check if it is working on moodle 4.3 or give me a hint. 
many thanks already for the plugin in general :-)
br 
Ole

For this text only the third line is not working 
{coursename}
{ifeditmode}EDITMODE !!!!{/ifeditmode} 
**{ifingroup 'US1'}USgruppe {/ifingroup 'US1'}**
{mygroups}:
![image](https://github.com/michael-milette/moodle-filter_filtercodes/assets/3253813/1e6bbde7-3127-4dd4-aa00-29c881760c24)

### What do you think should have happened?

I expected a hint if i used the plugin not correct

### Steps to reproduce

1. Login as 'admin/trainer/student
2. verified on two different moodle installation

### Moodle version

4.3

### Installed Moodle UI Language packs.

- [X] English only
- [X] One or more other languages/regional dialects (specify below)
- [ ] Other

### System information

Client Device type: (e.g. Desktop, iPhone or iPad, Android phone or tablet, Other - specify)
Client Operating System: (e.g. Windows, Linux, Mac OS, Android, iOS, Other - specify)
Client Web Browser: (e.g. Chrome, Edge, Firefox, Safari, Safe Exam Browser, Moodle Mobile App)
Server Operating System: (e.g. Windows, Linux, Mac OS, Other - specify)
Server Webserver: (e.g. Apache, Nginx, IIS, Other - specify)
Server PHP: (e.g. 7.4, 8.0, 8.1, 8.2, 8.3, Other - specify)

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @olemde ,

Try this...

{ifingroup us1}USgruppe {/ifingroup}

No quotation marks and no name in the closing tag. The specified group name needs to be the group's shortname and be in lowercase (not sure if uppercase will work).

I am travelling today from Moodlemoot Canada 2024 so I can't test this for you at the moment.

Let me know how it works out. Hope you find this information helpful.

Best regards,

Michael Milette

**Comment by olemde** [comment]
Hello Michael.

hope you had a save trip home.Thank you for your fast reply. With your help i could manage it:

 

1. the closing tag

2. my selected group was hidden. I am not sure if this is somewhere described. may it could help others if so.

 

best regards


Ole Messing

 
 

Gesendet: Freitag, 03. Mai 2024 um 18:25 Uhr
Von: "Michael Milette" ***@***.***>
An: "michael-milette/moodle-filter_filtercodes" ***@***.***>
Cc: "olem_de" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [michael-milette/moodle-filter_filtercodes] Bug: ifingroup ID does not work (Issue #297)


 

Hi @olemde ,

Try this...

{ifingroup us1}USgruppe {/ifingroup}

No quotation marks and no name in the closing tag. The specified group name needs to be the group's shortname and be in lowercase (not sure if uppercase will work).

I am travelling today from Moodlemoot Canada 2024 so I can't test this for you at the moment.

Let me know how it works out. Hope you find this information helpful.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
Hi @olemde ,

Thanks for letting me know. Glad to hear that you got it working.

Please note that I edited your message. When you reply using email, it includes the original message as well as a link to unsubscribe. I suspect this was not your intention.

I am closing this ticket as it sounds like it has been resolved. Feel free to create another Issue if you have any further questions.

Best regards,

Michael
