### ISSUE TITLE
Bug: {qrcode} and {urlencode} not processed after replacement tags

### ISSUE THREAD

**Issue by 28Smiles** [michael-milette/moodle-filter_filtercodes#302]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [X] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

Using tags within `urlencode` or `qrcode` are not replaced with their content and whitespace is encoded with `+` instead of `%2B` (Unlike specified in RFC 3986).
Example:
`{urlencode}Test {coursename}{/urlencode}`
Result:
`Test+%7Bcoursename%7D`

For a RFC 3986 compliant encoding use `rawurlencode`, either we change this or provide an additional tag.

### What do you think should have happened?

I expected `Test%2BThis%2Bis%2Ba%2Bcourse`

### Steps to reproduce

1. Create a course
2. Create an activity
3. Enable the filter
4. Use the sample provided (`{urlencode}Test {coursename}{/urlencode}`)
5. Save
6. Look at the result

### Moodle version

Moodle 4.4.2+

### Installed Moodle UI Language packs.

- [X] English only
- [ ] One or more other languages/regional dialects (specify below)
- [ ] Other

### System information

Client Device type: (e.g. Desktop, iPhone or iPad, Android phone or tablet, Other - specify)
Client Operating System: (e.g. Windows, Linux, Mac OS, Android, iOS, Other - specify)
Client Web Browser: (e.g. Chrome, Edge, Firefox, Safari, Safe Exam Browser, Moodle Mobile App)
Server Operating System: (e.g. Windows, Linux, Mac OS, Other - specify)
Server Webserver: (e.g. Apache, Nginx, IIS, Other - specify)
Server PHP: (e.g. 7.4, 8.0, 8.1, 8.2, 8.3, Other - specify)

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by 28Smiles** [comment]
If you tell me which version you prefer, I would try to file a patch

**Comment by michael-milette** [comment]
Hi @28Smiles ,

Sorry, for not responding sooner. I was off sick. 

I did take a look at your issue and was able to understand and reproduce it. The bug is a matter of code execution order. The {coursename} tag needs to be processed before the {urlencode} tags. It is a matter of shifting code around. Last year I though I worked through this for most tags but I guess this one escaped me.

You are welcome to submit a PR. However, I am not clear about your question regarding "which version I prefer". Can you clarify?

Best regards,

Michael

**Comment by 28Smiles** [comment]
The php function `urlencode` is not the one adhering to RFC 8936, therefore it would be nice to use `rawurlencode` either by changing the implementation or creation of a new tag for this version.

**Comment by michael-milette** [comment]
Thank you Leon for fixing this issue.
