### ISSUE TITLE
Feature Request: Create {ifnotincohort CohortID|idnumber}

### ISSUE THREAD

**Issue by Roelland** [michael-milette/moodle-filter_filtercodes#307]
### Prerequisites

- [X] I am requesting the new feature to the correct repository.
- [X] I checked the latest version on GitHub and the [README.md](../blob/master/README.md) documentation to ensure that this functionality does not already exist.
- [X] I searched to make sure that this feature has not already been requested.
- [X] I have, or I know someone who has, the ability and willingness to test the new feature on a Moodle LMS-based site.
- [X] I agree to submit one feature request per issue ticket (do not submit multiple requests in one issue ticket).
- [X] I understand that development and support is provided by volunteer(s) and that all final implementation decisions are up TNG Consulting Inc.

### Feature Request - The User Story

I'm an admin at a small Dutch academy. We tend to have a "one-size-fits-most" mentality in our courses. The activities are slightly tweaked depending on the cohort. For instance, we have cohorts like 'Data Analyst' and 'Cybercrime.' The core assignment remains the same, but the introductory text is modified slightly to suit each department, giving it a more personal touch. 

### Alterative you have considered

We currently achieve this using {ifingroup} and {ifnotingroup} functions. However, since we operate in cohorts, while it's possible to automate users into groups based on their cohort, we're hoping you could assist us in developing an **{ifnotincohort} function** that works similarly to {ifnotingroup}.

### Planning on submitting a solution in a pull request (PR)?

Maybe

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Thanks for the suggestion @Roelland ,

Closing this ticket as the new {ifnotincohort}{/ifnotincohort} tags have been added in FilterCodes 2.6. Please feel free to re-open this ticket if it doesn't meet your needs.

Best regards,

Michael Milette
