### ISSUE TITLE
Bug: PHP Fatal error:  Duplicate declaration of static variable $mycohorts in /var/www/moodle/filter/filtercodes/classes/text_filter.php on line 4311

### ISSUE THREAD

**Issue by mputzi** [michael-milette/moodle-filter_filtercodes#308]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [X] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

Upgrade of plugin stopped; site left unusable.

### What do you think should have happened?

I expected the upgrade of the plugin to finish smoothly.

### Steps to reproduce

1. Login as admin
2. Go to upgrade plugins
3. nothing happens, site not loading
4. Upgrading via cli
5. See fatal error message on console

### Moodle version

4.4.3 (Build: 20240902)

### Installed Moodle UI Language packs.

- [ ] English only
- [X] One or more other languages/regional dialects (specify below)
- [ ] Other

### Workaround

renaming variable in text_filter.php line 4311 and following lines of code block

### System information

Client Device type: Desktop
Client Operating System: Linux
Client Web Browser: any
Server Operating System: Linux
Server Webserver: NGinx
Server PHP: 8.3

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by jimsihk** [comment]
Same error on Moodle 4.4.4 (Build: 20241007), tried with a fresh copy of Moodle, once attempted to enable the filtercodes filter, Moodle will crash with same error.

**Comment by odelhaye** [comment]
Same fatal error on Moodle 4.5  (Build: 20241007). Php 8.3.9.

**Comment by michael-milette** [comment]
Thank you for your contribution. The issue has been resolved and will be included in the next release of FilterCodes (which should be in a few minutes).

**Comment by odelhaye** [comment]
Ça fonctionne impec désormais. Merciii !
