### ISSUE TITLE
Feature Request: Filter categories to be used on quizs using tags

### ISSUE THREAD

**Issue by Danimarqz** [michael-milette/moodle-filter_filtercodes#313]
### Prerequisites

- [X] I am requesting the new feature to the correct repository.
- [X] I checked the latest version on GitHub and the [README.md](../blob/master/README.md) documentation to ensure that this functionality does not already exist.
- [X] I searched to make sure that this feature has not already been requested.
- [X] I have, or I know someone who has, the ability and willingness to test the new feature on a Moodle LMS-based site.
- [X] I agree to submit one feature request per issue ticket (do not submit multiple requests in one issue ticket).
- [X] I understand that development and support is provided by volunteer(s) and that all final implementation decisions are up TNG Consulting Inc.

### Feature Request - The User Story

Hi, I'd like to build / modify the quiz plugin in order to let students generate their own quizs and i'd like to filter the questions they can use.
For example, id like to categorize questions by category and tag. The quizs that have the tag '1' can use questions with the same exact tag (from all categories).
So I was wondering if this kind of filtering is possible.

### Planning on submitting a solution in a pull request (PR)?

No

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @Danimarqz ,

That is not something that would fit into FilterCodes. However, you may be able to do that using question banks where quiz 1 would only be able to use use questions from question bank 1.

As for enabling students to create their own quiz, I have seen this done where a teacher will enable students to create their own course which can contain a quiz. However, you may also be able to accomplish this by creating en empty quiz activity for each student and then giving them permission add questions from a question bank associated with that particular quiz. You can also use an availability condition to control access and visibility to specific students.

Hope you find this information helpful.

Best regards,

Michael
