### ISSUE TITLE
Too many missing strings

### ISSUE THREAD

**Issue by mudrd8mz** [michael-milette/moodle-filter_filtercodes#5]
Have you had developer debugging enabled when testing the filter?

It seems to warn about many missing strings - especially those starting with "default" such as "defaultsurname" etc.

![image](https://user-images.githubusercontent.com/85831/28278069-1ee87982-6b1c-11e7-976a-a2de0597086b.png)

**Comment by michael-milette** [comment]
Hi @mudrd8mz,

Yikes! Thanks for pointing that out David. Yes, I usually live with debugging mode turned on in Moodle. However, just before pushing this out, I was working on the documentation and decided to renamed the variables in the code and documentation to make them more user friendly but forgot to rename them in the language file.

I will fix that as well as apply the other excellent suggestions you made and let you know as soon as an update becomes available. I should get to it within the next 6-12 hours.

Thanks again for all your suggestions. I always appreciate your wisdom and your feedback is always welcome. It helps me be a better Moodle developer.

**Comment by michael-milette** [comment]
The issue has been resolved and now works correctly.
