### ISSUE TITLE
Feature Request: custom roles (was Bug: custom roles not recognised)

### ISSUE THREAD

**Issue by jb-fol** [michael-milette/moodle-filter_filtercodes#55]
Am I right in thinking that custom roles are not recognised?
Eg. {ifteacher}{/ifteacher} works, but {ifnewroleshortname}{/ifnewroleshortname} does not appear to work... or am I missing something obvious?

**Comment by jb-fol** [comment]
Um, sorry - just found the answer in the documentation... but...!

Surely, using archetypes will be problematic for larger sites with custom roles? Have you seen the role filter that @andrewhancox has developed? https://github.com/andrewhancox/filter_role - this allows content to be shown/hidden for specific roles based on role shortname. Any mileage in combining efforts?

**Comment by michael-milette** [comment]
Hi @jb-fol , Happy new Year!

As you discovered, the plugin currently only includes support for Moodle archetypes for simplicity and performance reasons.

Thank you for your suggestion as well as bringing @andrewwhancox's approach to my attention. I can certainly see how integrating such a feature into Filtercodes could be useful. I will definitely keep it in mind for future releases of the plugin. :-)

Best regards,

Michael

**Comment by jb-fol** [comment]
Just wondering if you given this any more thought Michael? The ability to target specific roles rather than archetypes would be a huge benefit, and would allow certain things, like database activity, to have different “permission” on content - read only, write only, read/write, not visible.

**Comment by andrewhancox** [comment]
@jb-fol I built this as a separated plugin - https://github.com/andrewhancox/filter_role

**Comment by michael-milette** [comment]
Hi @andrewhancox , I tried your plugin but could not get it to work in Moodle 3.8,3. Can you confirm that it still works?

Based on the feedback from David Mudrák from a few years ago in your issue tracker on GitHub and from what I could see in the source code, I submitted a pull request to updated the README.md file based on my understanding of the source code but it still doesn't work,

**Comment by michael-milette** [comment]
Hi @jb-fol , the latest version of FilterCodes here on GitHub includes some new tags called:

{ifcustomrole roleshortname}{/ifcustomrole}

{ifnotcustomrole roleshortname}{/ifnotcustomrole}

Be sure to replace "roleshortname" with the short name of the role you want to test against,

I suspect that this may better suit your needs. I will be releasing this new version on Moodle.org within the next couple of days however, if you have a chance, I would appreciate it if you would be so kind as to give them a try and send me your feedback as soon as possible.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @jb-fol ,

It has been a few months since the release of FilterCodes 2.0 which included the new {ifcustomrole} and {ifnotcustomrole} tags. As I haven't heard back from you, I will assume that everything is working well and will close this ticket.

If you have a bug to report, please feel free to open a new ticket. Thanks again for your suggestion.

Best regards,

Michael
