### ISSUE TITLE
testen 3.3: feedback

### ISSUE THREAD

**Issue by gemguardian** [michael-milette/moodle-filter_filtercodes#6]
Hello Michael,

I have tested the filter code plugin on a local 3.3 .
First off all I really like this plug-in. I normally would use Generico for it, since I could use the code pieces and then make a button for teacher to use, so they don't have to memorize the shortcodes. 

Below some feedback: 

Moodle metadata filters: worked as expected, there where no issues

Conditionally display content filters:
I have not tested them all. But:

-  the {ifstudent}{/ifstudent}  did not work for me. I checked if the student had higher permissions but that was not the case. 

- {ifenrolled} is nice, but when I am not enrolled and look as a guest then I see the code and by example the image. see enclosed screenshot.

![test_ifenrolled](https://user-images.githubusercontent.com/16559999/30099788-0e8664d0-92e7-11e7-910c-0e4106a86cfd.png)

Gemma

**Comment by michael-milette** [comment]
Hi @gemguardian 

Thank you for your feedback Gemma. I really appreciate it. Both of the issues you mentioned have been addressed. In the process, I also noticed that the {ifnotenrolled} tags were affected by the same bug as the {ifenrolled} tags. Both are now fixed.

The way the existing {if...} tags work is now a little different. They will no longer display content if you have a higher level role than the one specified. For example, {ifteacher}Content here!{/ifteacher} will now display the words "Content here!" only if the user actually has been assigned a teacher role regardless of whether they are a manager or administrator. If an administrator is not a teacher, the content will not appear.

To make up for this, I have added 4 new sets of tags including:

{ifminassistant}{/ifminassistant}
{ifminteacher}{/ifminteacher}
{ifmincreator}{/ifmincreator}
{ifminmanager}{/ifminmanager}

These now work more like the original non-ifmin tags did in the previous version. For example, {ifminteacher}Content here!{/ifminteacher} will now display the words "Content here!" as long as the user has been assigned a role which is either a teacher, course creator, manager or administrator. So administrators will see the content even if the have not been explicitly assigned a teacher role in the course.

One other change is that FilterCodes no longer uses capabilities to try and guess the role of the user. It now checks whether a role has been assigned to the user. This will improve consistency of the filters as they will no longer be affected  by changes to the capabilities of a role.

Last but not least, I want to acknowledge your suggestion of including an Atto extension to make it easier to insert FilterCodes. I think it is an excellent suggestion and will look into implementing this as a separate plugin, like Generico does, in the future.

Thanks again for your feedback. It is much appreciated. Let me know if you find anything else or have any questions.

Best regards,

    Michael

**Comment by michael-milette** [comment]
Hi @gemguardian ,

Forgot to mention. One other new feature I added is that the {if...} tags are now aware of switching roles. This should make it easier test and to preview results.

Best regards,

    Michael

**Comment by gemguardian** [comment]
Great. I will test this version next week 


Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Michael Milette <notifications@github.com> Datum: 08-09-17  18:21  (GMT+01:00) Aan: michael-milette/moodle-filter_filtercodes <moodle-filter_filtercodes@noreply.github.com> Cc: gemguardian <gemma@ltnc.nl>, Mention <mention@noreply.github.com> Onderwerp: Re: [michael-milette/moodle-filter_filtercodes] testen 3.3: feedback
  (#6) 
Hi @gemguardian ,
Forgot to mention. One other new feature I added is that the {if...} tags are now aware of switching roles. This should make it easier test and to preview results.
Best regards,
Michael


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/michael-milette/moodle-filter_filtercodes","title":"michael-milette/moodle-filter_filtercodes","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/michael-milette/moodle-filter_filtercodes"}},"updates":{"snippets":[{"icon":"PERSON","message":"@michael-milette in #6: Hi @gemguardian ,\r\n\r\nForgot to mention. One other new feature I added is that the {if...} tags are now aware of switching roles. This should make it easier test and to preview results.\r\n\r\nBest regards,\r\n\r\n    Michael"}],"action":{"name":"View Issue","url":"https://github.com/michael-milette/moodle-filter_filtercodes/issues/6#issuecomment-328149616"}}}
