### ISSUE TITLE
Feature Request: display profile field

### ISSUE THREAD

**Issue by Th0rstein** [michael-milette/moodle-filter_filtercodes#65]
It would be great if filter codes could display any profile field (especially custom ones) besides the few basics like First Name and Lastname. Using a similar syntax to the userpictureimg filter code e.g. {profile fieldname}.

**Comment by michael-milette** [comment]
Hi @Th0rstein ,

Thank you for taking the time to submit your excellent suggestion. I will definitely see if I can include this feature in the next release of FilterCodes - scheduled to come out around November 2018, usually about a week or so before the next release of Moodle 3.6.

If you need it sooner, my services are available in exchange for financial support.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @Th0rstein ,

I was just wondering if you had a chance to checkout the new profile fields in the current release of FilterCodes. Let me know if they satisfy your needs.

Best regards,

Michael

**Comment by michael-milette** [comment]
As I have not received any feedback, I am closing this issue.
