### ISSUE TITLE
Feature Request: IDNumber

### ISSUE THREAD

**Issue by scotthardwick** [michael-milette/moodle-filter_filtercodes#71]
Please add the ability to have the student's idnumber available as a {filter]

**Comment by michael-milette** [comment]
Hi @scotthardwick ,

Thanks for the suggestion. I will try to include this in the upcoming release of FilterCodes.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @scotthardwick,

There is now a new {idnumber} field available in FilterCodes. It is only available here on GitHub at the moment but will be included in the next official release coming up in May. Feel free to try it out and let me know if you run into any problems with the new tag.

Best regards,

Michael

**Comment by scotthardwick** [comment]
Thanks so much Michael!  I just tried this and it works great ;-) I appreciate this!
