### ISSUE TITLE
A Note for Others

### ISSUE THREAD

**Issue by scotthardwick** [michael-milette/moodle-filter_filtercodes#73]
Not sure if anyone else is using the BoostNavigation plugin, but I don't know if there are possible conflicts.  That plugin also allow placeholders which allow items to be in the Boost Navigation system.

https://github.com/moodleuulm/moodle-local_boostnavigation

{courseid}: The course's (internal) ID
{courseshortname}: The course's shortname
{coursefullname}: The course's full name
{editingtoggle}: The value 'on' or 'off' which is needed to toggle edit mode
{userid}: The logged in user's (internal) ID
{userusername}: The logged in user's username
{userfullname}: The logged in user's full name
{pagecontextid}: The current page's context ID
{pagepath}: The current page's URL path
{sesskey}: The sesskey to use in secured URLs

Not sure how both install together may or may not clash.

**Comment by michael-milette** [comment]
Hi @scotthardwick ,

Have you tried it to see if there are any conflicts?

Most of the tags you mentioned are also supported in FilterCodes.

Some are a little different such as userusername (simply username in Filtercodes) and userfullname (simply fullname in Filtercodes). 

The only one really that is not supported is {pagecontextid}. I wouldn't mind adding it but I would need a user story (example) of how it might be used.

Give it a try and let me know.

Best regards,

Michael

**Comment by michael-milette** [comment]
As I have not received any feedback in a while, I am closing this issue.
