### ISSUE TITLE
Feature request: {ifincohort xxx}{/ifincohort}

### ISSUE THREAD

**Issue by michael-milette** [michael-milette/moodle-filter_filtercodes#74]
Add a conditional tag that would check to see if the user is a member of a cohort.

**Comment by jb-fol** [comment]
This would be a very welcome addition :)

I'd like to be able to show content in a. course to members of a cohort enrolled in that course.

**Comment by argwallace** [comment]
I agree! This would be a great addition to an already great plugin! We use cohorts in several ways and being able to tap into this info would give us many possibilities.

**Comment by michael-milette** [comment]
The new {ifincohort} tag is now available on GitHub and will be included in the next release of FilterCodes on Moodle.org in November 2020. If you have a chance, I would appreciate it if you would be so kind as to test it to ensure that it is working for you.

FYI: The required parameter can either be the ID of the cohort or the idnumber field as defined in the cohort's settings.

Examples:

{ifincohort moodlers}You are a Moodler!{/ifincohort}

{ifincohort 1}You are a Moodler!{/ifincohort}

... where the id of the **moodlers** cohort is 1 and the id number setting for this cohort is set to **moodlers**.

Thanks go to @jb-fol and @argwallace for their suggestion of this new feature. Hope you find it useful.

Best regards,

Michael Milette

**Comment by argwallace** [comment]
Thank you! I will tear this and let you know. Appreciate that you were able to incorporate this into FilterCodes. 

Stephen
argwallace

**Comment by argwallace** [comment]
Michael,

How to you force an update to the Moodle database when using newer code but the version is still referencing the old? My Moodle doesn’t trigger an update. Is there a way to do that manually?

Thanks,

Stephen

**Comment by michael-milette** [comment]
You don't need to. There was no change to the database. Just copy the files in place and it will work. :-)

The version number will change when I release it on Moodle.org.

**Comment by michael-milette** [comment]
In fact, the only file that does anything, which has changed so far, is filter.php. Copy that file into place and you are good to go.

**Comment by argwallace** [comment]
Hey,

Thanks for the info. I have tried the {ifincohort XXX}Test{/ifincohort} tag and have found the following:

1. If I use the id number it works fine.
2. If I use the id name, it doesn’t work.

Am I missing something?

Thanks for your work on this and I’m glad to help test it to help.

Stephen

**Comment by michael-milette** [comment]
Hi @argwallace 

Thank you for testing this out. I am not sure what the problem is however here are a few things to check:

1) You are using the Cohort ID and not the Name. It was probably confusing of me to include the word "name" in the documentation. I will need to rethink that.
![image](https://user-images.githubusercontent.com/3808579/95077715-f56e8000-06e1-11eb-92ba-fe7b19714cdc.png)

2) The Cohort ID is case sensitive.

3) The Cohort ID must be one word which can contain letters (a to z, A to Z), numbers (0 to 9) and underscores. Spaces and Dashes and other special characters are not currently supported.

Please let me know if the problem was one of these so that I can take your feedback into consideration.

Best regards,

Michael

**Comment by argwallace** [comment]
Ok, that makes more sense now. Yes, that’s what it was. I was using the Name rather than the Cohort ID.

Thanks!

Stephen
