### ISSUE TITLE
Feature Request: Topic/Section filtercode

### ISSUE THREAD

**Issue by behoof** [michael-milette/moodle-filter_filtercodes#78]
L.s.

Is it possible to have a filter code which is referring to the section page? 

Example: When entering a page activity on a section page (e.g. Grid course format), users are often lost. I want to add a filtercode on top of the page which refers to the section, so users can return to the section page instead of the course page.

That would end a lot of our user complaints about the user interface.

Bert

**Comment by michael-milette** [comment]
Hi Bert,

Thanks for taking the time to contribute your idea. It sounds like a good one. I am trying to visualize this and wondering, are you asking for a filter code which turns into a URL or the name of the section that they are currently in?

Best regards,

Michael

**Comment by behoof** [comment]
Hi Michael,

In fact the section-id. See what I'm doing in: [https://ispri.ng/Bg7JD](https://ispri.ng/Bg7JD) 

Does this help?

Best regards

Bert

**Comment by michael-milette** [comment]
Hi Bert,

It does indeed! Sounds like it would be useful too. Leave that with me and I will see what I can do about it. If I have time, I will try to get to it before the next release coming up in May. I will let you know as soon as I have something for you to test, hopefully before then.

Best regards,

Michael

**Comment by michael-milette** [comment]
Please also leave that link to your presentation available if possible.

**Comment by behoof** [comment]
Ok

Met vriendelijke groet,

Bert van der Hooft
Telefoon 06 11 11 9405

________________________________
Van: Michael Milette <notifications@github.com>
Verzonden: donderdag, maart 28, 2019 6:22 PM
Aan: michael-milette/moodle-filter_filtercodes
CC: Bert van der Hooft; Author
Onderwerp: Re: [michael-milette/moodle-filter_filtercodes] Feature Request: Topic/Section filtercode (#78)


Please also leave that link to your presentation available if possible.

**Comment by behoof** [comment]
Top!

Met vriendelijke groet,

Bert van der Hooft
Telefoon 06 11 11 9405

________________________________
Van: Michael Milette <notifications@github.com>
Verzonden: donderdag, maart 28, 2019 6:21 PM
Aan: michael-milette/moodle-filter_filtercodes
CC: Bert van der Hooft; Author
Onderwerp: Re: [michael-milette/moodle-filter_filtercodes] Feature Request: Topic/Section filtercode (#78)


Hi Bert,

It does indeed! Sounds like it would be useful too. Leave that with me and I will see what I can do about it. If I have time, I will try to get to it before the next release coming up in May. I will let you know as soon as I have something for you to test, hopefully before then.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi Bert.

Turned out to be a lot simpler than I thought. If you want to give it a try, download the filtercodes plugin from GitHub. I also included a couple of useful "Back" button type examples in the documentation.

There are two new tags: {sessionid} and %7Bsessionid%7D. This last one can be useful when including the filtercode tag in a URL. These new tags will be added on Moodle.org along with a few others when I release the next version just before the upcoming launch of Moodle 3.7 in May 2019.

If you have a chance, I would appreciate it if you would be so kind as to let me know if meets your needs.

Enjoy!

Michael

**Comment by behoof** [comment]
Tested and applied the back button in production! Marvellous! A ten years old remark of my students solved!

Thanks!

Bert

**Comment by michael-milette** [comment]
Thanks for testing!

When I was doing testing, it was kind of nice because it follows section numbers as you move the sections around. Thanks again for your suggestion and the presentation. It was a great idea and very helpful.

Best regards,

Michael

**Comment by behoof** [comment]
Michael, 

A tip for your documentation for the code: 

<p style="float:right;"><a href="{wwwroot}/course/view.php?id={courseid}&amp;section={sectionid}" class="btn btn-outline" style="font-size:14px;">Go Back</a></p>

Is not working in the Buttons Course Format (which is logical). 

In that case I use:

<p style="text-align: right; "><a href="{wwwroot}/course/view.php?id={courseid}" _blank"="" class="btn btn-outline" style="font-size: 14px;">HOME</a></p>

Bert
