### ISSUE TITLE
Missing string pluginname

### ISSUE THREAD

**Issue by ewallah** [michael-milette/moodle-filter_filtercodes#79]
The language file is missing the plugin name string. As a result the plugins update page and email contain codes like {\}.

Just add $string['pluginname'] = 'filtercodes filter'; to the language file.

**Comment by michael-milette** [comment]
Hi @ewallah , you are absolutely correct. An oversight on my part. I have addressed the issue with the following commit: https://github.com/michael-milette/moodle-filter_filtercodes/commit/4dabf4969b9e8d5cd4df5912eae8b314cc75553c

Thanks for taking the time to report this issue. Much appreciated.

Best regards,

Michael Milette

**Comment by ewallah** [comment]
THX for the fix!
