### ISSUE TITLE
Feature request {ifsection}

### ISSUE THREAD

**Issue by collinsconstruction** [michael-milette/moodle-filter_filtercodes#80]
I have a course where:
Format = Topics Format
Course layout = Show one section per page

The course has multiple Topics, where:
Summary = several paragraphs of text

Currently, there is no way to control whether the summary text appears on the course page, or the section page, or both.  There is also no way to specify a PORTION of the summary to only appear on either the course or section page.

I propose some new filtercodes:

{ifcourse} - display only on the course page
{ifsection} - display only the section page
Possibly others, for different course formats

These filters could also operate on Activity descriptions.

**Comment by michael-milette** [comment]
Hi @collinsconstruction ,

I coded up some new tags, as per your suggestion, but didn't have time to test so I have no idea whether it will work or not. If you feel like trying it out, let me know if it works for you. It is currently only here on GitHub for now.

On a side note, I only implemented it for courses and not the Front Page (Home) - which internally is actually a Moodle course too.

Hope this helps.

Best regards,

Michael

**Comment by collinsconstruction** [comment]
Hi Michael

Thanks!  I installed and tried it.  The filtercodes in {} are processed (the curly brace content disappears).
However, the content to be displayed doesn't show.

With regard to {isincourse}, I am actually not sure under what circumstances that text should appear!

**Comment by michael-milette** [comment]
{Ifcourse} could be used, for example, if you had a block appearing site-wide but only wanted some content to show up if within a course.

**Comment by michael-milette** [comment]
Thank you for letting me know about no content showing up. I will look into it hopefully within the next few days.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @collinsconstruction , I tried to reproduce the issue with content not showing up but cannot reproduce it. Can you please provide me with the steps to reproduce the problem?

**Comment by michael-milette** [comment]
Hi @collinsconstruction ,

One more thing. I am not sure if this will help but I added a new set of {ifnotinsection}{/ifnotinsection} tags which will allow you to display something in a course if you are in the course outline and not in a section of the course.

The new {ifnotinsection}{/ifnotinsection} tags will be added on Moodle.org along with a few others when I release the next version just before the launch of Moodle 3.8 in November 2019.

In the meantime, if you have a chance, I would appreciate it if you would try out the latest version on GitHub which includes this new tags and let me know if meets your needs.

Best regards,

Michael
