### ISSUE TITLE
Feature request: {courseidnumber}

### ISSUE THREAD

**Issue by acquaalta** [michael-milette/moodle-filter_filtercodes#81]
Hi Michael,
"Filter Codes" is a great plugin for Moodle. Thanks for creating it.

Is it possible that you will add to the plugin a "Course ID Number" tag?
The plugin already has the {courseid} tag, but it relates to the ID determined by Moodle, and not to the custom ID number of the course that is determined by the user.

Some external systems in my institute use the internal course numbers as a parameter in the URL addressed that they produce, and if I could place this number number in a URL in Moodle, I could create dynamic links.

Yeah, I know that I can use variables inside a URL activity, and it includes "Course ID number" as an option, but I actually want to use this mechanism in another area of Moodle.

Thanks in advance :-)

**Comment by michael-milette** [comment]
Hi @acquaalta,

Thank you for requesting this feature. However it is not clear to me what you mean by "custom ID number of the course that is determined by the user".

Could you please provide me with detailed instructions and a screenshot if possible to help me better unserstand what you are asking for?

Best regards,

Michael

**Comment by acquaalta** [comment]
Hi Michael,
Please see the attached screenshot:
The "Course ID" is the "id" parameter present in the Course page URL, and refers to the ID created automatically by Moodle in its database.
The "Course ID number" is the setting present in the "Edit Settings" page of a course, and can be determined by the user.

![Moodle - Course ID vs Course ID number](https://user-images.githubusercontent.com/51836675/59551037-1dc9ec80-8f7c-11e9-9208-39d4e136ca71.png)

**Comment by michael-milette** [comment]
Thanks for the explanation and the screenshot. What confused me is when you said students could enter the number. Students don't normally have access to edit course settings, only teachers and above.

This is a good suggestion. I will be sure to add it in a future release of FilterCodes.

**Comment by acquaalta** [comment]
Oh, by "user" I was referring only to the teaching roles. I should be more clear next time :-)

Thanks for taking my suggestion into consideration.

**Comment by michael-milette** [comment]
Hi @acquaalta ,

The new {courseidnumber} tag will be added on Moodle.org along with a few others when I release the next version just before the launch of Moodle 3.8 in November 2019.

In the meantime, if you have a chance, I would appreciate it if you would try out the latest version on GitHub which includes this new tag and let me know if meets your needs.

**Comment by acquaalta** [comment]
Hi Michael,
Thanks for implementing this feature. I updated filter.php with the new code, but it doesn't seems to work for some reason. Instead of the Course ID Number I see no text at all.

I verified that the relevant code is "active" - I changed filter.php in the server so "$PAGE->course->idnumber;" would be "$PAGE->course->id;", refreshed a test page in Moodle, and saw that what was empty text before now showed the internal Moodle ID of the course. So it has to be something with the idnumber field that the code reference to.

**Comment by michael-milette** [comment]
Hi @acquaalta ,

Unfortunately I am unable to reproduce your issue with the {courseidnumber} tag. Here is how I tested it:

1. Create a new course.
2. Give it a course ID number. I used TEST01.
3. Save your settings.
4. Add an HTML block to your course main page.
5. Edit the content of the HTML block and add the following:
{getstring}idnumbercourse{/getstring} : {courseidnumber}
6. Save.

View the course page. You should see:

Course ID number : TEST01

If you don't see the "Course ID number" string, then you are either using an old version of FilterCodes or you have not enabled FilterCodes correctly in Manage Filters. However since you did that second test, I am assuming that FilterCodes is enabled and correctly configured.

You will need to give me more information about your system. To start off:

- What version of Moodle are you using?
- Where are you adding the code snippet exactly?

**Comment by michael-milette** [comment]
Hi @acquaalta 

Just a friendly reminder that I am still waiting to hear from you with more information to help me reproduce your issue.

Best regards,

Michael

**Comment by acquaalta** [comment]
Hi Michael,
This time I pulled the current build of the plugin via Git, into a clean server, and the plugin seems to work fine :-)
![tymm](https://user-images.githubusercontent.com/51836675/64921457-ff1e0080-d7cb-11e9-85cd-7f13e0defe32.png)

Thanks a lot :-)

**Comment by michael-milette** [comment]
Hi @acquaalta , that would be it. Until I the next release scheduled for November 2019, the new functionality only exists here on GitHub for testing purposes.

Glad to hear you got it working.

Best regards,

Michael
