### ISSUE TITLE
Feature Request: {activityname}

### ISSUE THREAD

**Issue by behoof** [michael-milette/moodle-filter_filtercodes#82]
Ls

I would appreciate {activityname} as a new feature, showing the name of the current activity.

Best regards,

Bert

**Comment by michael-milette** [comment]
Hi @behoff,

Interesting. Could you please give me an example of how this would be used?

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @behoof , haven't heard from you in a while. Just wondering if you might be able to provide an example of how an {activityname} would be used.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @behoof , as it has been several months since I last heard from you, I will close this ticket. Please let me know if you feel it needs to be re-opened.
