### ISSUE TITLE
Feature Request: User Description tag

### ISSUE THREAD

**Issue by jb-fol** [michael-milette/moodle-filter_filtercodes#97]
Would there be a possibility to pull through the "User Description" field with a new filtercode?

**Comment by michael-milette** [comment]
Thank you @jb-fol for your suggestion. Can you give me an example of how you might use this new filtercode?

**Comment by michael-milette** [comment]
Closing this issue as there has been no response to the request for more information from @jb-fol since January 2020.

**Comment by jb-fol** [comment]
Oops sorry, missed this. Broke my wrist and was out of action for a while.

Description would be useful for me as I use FilterCodes extensively and one use case is that we hide the description box from the user profile to prevent learner editing, but populate it from an external database. Filtercodes would allow me to show the description and other user data on a page or in a block.

Appreciate that this is a fairly unique case though, so don’t worry too much if it’s too much hassle.

**Comment by michael-milette** [comment]
Hi @jb-fol ,

The new {userdescription} tags you requested has been added to FilterCodes on GItHub and will be released on Moodle.org along with many other new tags just before the launch of Moodle 3.8 in June 2020 next week (est. June 15).

If you have a chance within the next few days, I would really appreciate it if you would be so kind as to try out the latest version which includes the new tag. Let me know if meets your needs.

Best regards,

Michael

**Comment by jb-fol** [comment]
Tested in various contexts on a Moodle 3.8.3 site and works as expected. Thank you very much.

**Comment by michael-milette** [comment]
Thanks @jb-fol !
